download-schemas:
  cmds:
    - generate/scripts/download-schemas.bash
    # Patch schemas
    - patch schemas/1.03/Opc.Ua.Types.bsd.xml misc/opc_ua_types_1_03.patch
  sources:
    - misc/opc_ua_types_1_03.patch
  generates:
    - schemas/1.03/*
generate-tools:
  cmds:
    - go get -u golang.org/x/tools/cmd/goimports
    - go install github.com/searis/guma/generate/cmd/opcua-xml2code
    - go install github.com/searis/guma/generate/cmd/csv2code
generate:
  deps:
    - download-schemas
    - generate-tools
  cmds:
    - go generate ./stack/uatype
