version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/searis/guma
    steps:
      - checkout
      - run: go get -u -v github.com/golang/dep/cmd/dep
      - run: go get -u -v github.com/go-task/task/cmd/task
      - run: dep ensure -no-vendor -dry-run
      - run: dep ensure
      - run: go test -v -race ./...
