// DO NOT EDIT. Generated by opcua-xml2code.

package uatype

import "time"

type enumNodeIdType byte

// BitLength returns the number of bits that should be used for encoding this value.
func (t enumNodeIdType) BitLength() int {
	return 6
}

// The possible encodings for a NodeId value.
const (
	NodeIdTypeTwoByte    enumNodeIdType = 0
	NodeIdTypeFourByte   enumNodeIdType = 1
	NodeIdTypeNumeric    enumNodeIdType = 2
	NodeIdTypeString     enumNodeIdType = 3
	NodeIdTypeGuid       enumNodeIdType = 4
	NodeIdTypeByteString enumNodeIdType = 5
)

type enumNamingRuleType uint32

const (
	NamingRuleTypeMandatory  enumNamingRuleType = 1
	NamingRuleTypeOptional   enumNamingRuleType = 2
	NamingRuleTypeConstraint enumNamingRuleType = 3
)

type enumOpenFileMode uint32

const (
	OpenFileModeRead          enumOpenFileMode = 1
	OpenFileModeWrite         enumOpenFileMode = 2
	OpenFileModeEraseExisting enumOpenFileMode = 4
	OpenFileModeAppend        enumOpenFileMode = 8
)

type enumTrustListMasks uint32

const (
	TrustListMasksNone                enumTrustListMasks = 0
	TrustListMasksTrustedCertificates enumTrustListMasks = 1
	TrustListMasksTrustedCrls         enumTrustListMasks = 2
	TrustListMasksIssuerCertificates  enumTrustListMasks = 4
	TrustListMasksIssuerCrls          enumTrustListMasks = 8
	TrustListMasksAll                 enumTrustListMasks = 15
)

type enumIdType uint32

// The type of identifier used in a node id.
const (
	IdTypeNumeric enumIdType = 0
	IdTypeString  enumIdType = 1
	IdTypeGuid    enumIdType = 2
	IdTypeOpaque  enumIdType = 3
)

type enumNodeClass uint32

// A mask specifying the class of the node.
const (
	NodeClassUnspecified   enumNodeClass = 0
	NodeClassObject        enumNodeClass = 1
	NodeClassVariable      enumNodeClass = 2
	NodeClassMethod        enumNodeClass = 4
	NodeClassObjectType    enumNodeClass = 8
	NodeClassVariableType  enumNodeClass = 16
	NodeClassReferenceType enumNodeClass = 32
	NodeClassDataType      enumNodeClass = 64
	NodeClassView          enumNodeClass = 128
)

type enumApplicationType uint32

// The types of applications.
const (
	ApplicationTypeServer          enumApplicationType = 0
	ApplicationTypeClient          enumApplicationType = 1
	ApplicationTypeClientAndServer enumApplicationType = 2
	ApplicationTypeDiscoveryServer enumApplicationType = 3
)

type enumMessageSecurityMode uint32

// The type of security to use on a message.
const (
	MessageSecurityModeInvalid        enumMessageSecurityMode = 0
	MessageSecurityModeNone           enumMessageSecurityMode = 1
	MessageSecurityModeSign           enumMessageSecurityMode = 2
	MessageSecurityModeSignAndEncrypt enumMessageSecurityMode = 3
)

type enumUserTokenType uint32

// The possible user token types.
const (
	UserTokenTypeAnonymous   enumUserTokenType = 0
	UserTokenTypeUserName    enumUserTokenType = 1
	UserTokenTypeCertificate enumUserTokenType = 2
	UserTokenTypeIssuedToken enumUserTokenType = 3
)

type enumSecurityTokenRequestType uint32

// Indicates whether a token if being created or renewed.
const (
	SecurityTokenRequestTypeIssue enumSecurityTokenRequestType = 0
	SecurityTokenRequestTypeRenew enumSecurityTokenRequestType = 1
)

type enumNodeAttributesMask uint32

// The bits used to specify default attributes for a new node.
const (
	NodeAttributesMaskNone                    enumNodeAttributesMask = 0
	NodeAttributesMaskAccessLevel             enumNodeAttributesMask = 1
	NodeAttributesMaskArrayDimensions         enumNodeAttributesMask = 2
	NodeAttributesMaskBrowseName              enumNodeAttributesMask = 4
	NodeAttributesMaskContainsNoLoops         enumNodeAttributesMask = 8
	NodeAttributesMaskDataType                enumNodeAttributesMask = 16
	NodeAttributesMaskDescription             enumNodeAttributesMask = 32
	NodeAttributesMaskDisplayName             enumNodeAttributesMask = 64
	NodeAttributesMaskEventNotifier           enumNodeAttributesMask = 128
	NodeAttributesMaskExecutable              enumNodeAttributesMask = 256
	NodeAttributesMaskHistorizing             enumNodeAttributesMask = 512
	NodeAttributesMaskInverseName             enumNodeAttributesMask = 1024
	NodeAttributesMaskIsAbstract              enumNodeAttributesMask = 2048
	NodeAttributesMaskMinimumSamplingInterval enumNodeAttributesMask = 4096
	NodeAttributesMaskNodeClass               enumNodeAttributesMask = 8192
	NodeAttributesMaskNodeId                  enumNodeAttributesMask = 16384
	NodeAttributesMaskSymmetric               enumNodeAttributesMask = 32768
	NodeAttributesMaskUserAccessLevel         enumNodeAttributesMask = 65536
	NodeAttributesMaskUserExecutable          enumNodeAttributesMask = 131072
	NodeAttributesMaskUserWriteMask           enumNodeAttributesMask = 262144
	NodeAttributesMaskValueRank               enumNodeAttributesMask = 524288
	NodeAttributesMaskWriteMask               enumNodeAttributesMask = 1048576
	NodeAttributesMaskValue                   enumNodeAttributesMask = 2097152
	NodeAttributesMaskAll                     enumNodeAttributesMask = 4194303
	NodeAttributesMaskBaseNode                enumNodeAttributesMask = 1335396
	NodeAttributesMaskObject                  enumNodeAttributesMask = 1335524
	NodeAttributesMaskObjectTypeOrDataType    enumNodeAttributesMask = 1337444
	NodeAttributesMaskVariable                enumNodeAttributesMask = 4026999
	NodeAttributesMaskVariableType            enumNodeAttributesMask = 3958902
	NodeAttributesMaskMethod                  enumNodeAttributesMask = 1466724
	NodeAttributesMaskReferenceType           enumNodeAttributesMask = 1371236
	NodeAttributesMaskView                    enumNodeAttributesMask = 1335532
)

type enumAttributeWriteMask uint32

// Define bits used to indicate which attributes are writable.
const (
	AttributeWriteMaskNone                    enumAttributeWriteMask = 0
	AttributeWriteMaskAccessLevel             enumAttributeWriteMask = 1
	AttributeWriteMaskArrayDimensions         enumAttributeWriteMask = 2
	AttributeWriteMaskBrowseName              enumAttributeWriteMask = 4
	AttributeWriteMaskContainsNoLoops         enumAttributeWriteMask = 8
	AttributeWriteMaskDataType                enumAttributeWriteMask = 16
	AttributeWriteMaskDescription             enumAttributeWriteMask = 32
	AttributeWriteMaskDisplayName             enumAttributeWriteMask = 64
	AttributeWriteMaskEventNotifier           enumAttributeWriteMask = 128
	AttributeWriteMaskExecutable              enumAttributeWriteMask = 256
	AttributeWriteMaskHistorizing             enumAttributeWriteMask = 512
	AttributeWriteMaskInverseName             enumAttributeWriteMask = 1024
	AttributeWriteMaskIsAbstract              enumAttributeWriteMask = 2048
	AttributeWriteMaskMinimumSamplingInterval enumAttributeWriteMask = 4096
	AttributeWriteMaskNodeClass               enumAttributeWriteMask = 8192
	AttributeWriteMaskNodeId                  enumAttributeWriteMask = 16384
	AttributeWriteMaskSymmetric               enumAttributeWriteMask = 32768
	AttributeWriteMaskUserAccessLevel         enumAttributeWriteMask = 65536
	AttributeWriteMaskUserExecutable          enumAttributeWriteMask = 131072
	AttributeWriteMaskUserWriteMask           enumAttributeWriteMask = 262144
	AttributeWriteMaskValueRank               enumAttributeWriteMask = 524288
	AttributeWriteMaskWriteMask               enumAttributeWriteMask = 1048576
	AttributeWriteMaskValueForVariableType    enumAttributeWriteMask = 2097152
)

type enumBrowseDirection uint32

// The directions of the references to return.
const (
	BrowseDirectionForward enumBrowseDirection = 0
	BrowseDirectionInverse enumBrowseDirection = 1
	BrowseDirectionBoth    enumBrowseDirection = 2
	BrowseDirectionInvalid enumBrowseDirection = 3
)

type enumBrowseResultMask uint32

// A bit mask which specifies what should be returned in a browse response.
const (
	BrowseResultMaskNone              enumBrowseResultMask = 0
	BrowseResultMaskReferenceTypeId   enumBrowseResultMask = 1
	BrowseResultMaskIsForward         enumBrowseResultMask = 2
	BrowseResultMaskNodeClass         enumBrowseResultMask = 4
	BrowseResultMaskBrowseName        enumBrowseResultMask = 8
	BrowseResultMaskDisplayName       enumBrowseResultMask = 16
	BrowseResultMaskTypeDefinition    enumBrowseResultMask = 32
	BrowseResultMaskAll               enumBrowseResultMask = 63
	BrowseResultMaskReferenceTypeInfo enumBrowseResultMask = 3
	BrowseResultMaskTargetInfo        enumBrowseResultMask = 60
)

type enumFilterOperator uint32

const (
	FilterOperatorEquals             enumFilterOperator = 0
	FilterOperatorIsNull             enumFilterOperator = 1
	FilterOperatorGreaterThan        enumFilterOperator = 2
	FilterOperatorLessThan           enumFilterOperator = 3
	FilterOperatorGreaterThanOrEqual enumFilterOperator = 4
	FilterOperatorLessThanOrEqual    enumFilterOperator = 5
	FilterOperatorLike               enumFilterOperator = 6
	FilterOperatorNot                enumFilterOperator = 7
	FilterOperatorBetween            enumFilterOperator = 8
	FilterOperatorInList             enumFilterOperator = 9
	FilterOperatorAnd                enumFilterOperator = 10
	FilterOperatorOr                 enumFilterOperator = 11
	FilterOperatorCast               enumFilterOperator = 12
	FilterOperatorInView             enumFilterOperator = 13
	FilterOperatorOfType             enumFilterOperator = 14
	FilterOperatorRelatedTo          enumFilterOperator = 15
	FilterOperatorBitwiseAnd         enumFilterOperator = 16
	FilterOperatorBitwiseOr          enumFilterOperator = 17
)

type enumTimestampsToReturn uint32

const (
	TimestampsToReturnSource  enumTimestampsToReturn = 0
	TimestampsToReturnServer  enumTimestampsToReturn = 1
	TimestampsToReturnBoth    enumTimestampsToReturn = 2
	TimestampsToReturnNeither enumTimestampsToReturn = 3
	TimestampsToReturnInvalid enumTimestampsToReturn = 4
)

type enumHistoryUpdateType uint32

const (
	HistoryUpdateTypeInsert  enumHistoryUpdateType = 1
	HistoryUpdateTypeReplace enumHistoryUpdateType = 2
	HistoryUpdateTypeUpdate  enumHistoryUpdateType = 3
	HistoryUpdateTypeDelete  enumHistoryUpdateType = 4
)

type enumPerformUpdateType uint32

const (
	PerformUpdateTypeInsert  enumPerformUpdateType = 1
	PerformUpdateTypeReplace enumPerformUpdateType = 2
	PerformUpdateTypeUpdate  enumPerformUpdateType = 3
	PerformUpdateTypeRemove  enumPerformUpdateType = 4
)

type enumMonitoringMode uint32

const (
	MonitoringModeDisabled  enumMonitoringMode = 0
	MonitoringModeSampling  enumMonitoringMode = 1
	MonitoringModeReporting enumMonitoringMode = 2
)

type enumDataChangeTrigger uint32

const (
	DataChangeTriggerStatus               enumDataChangeTrigger = 0
	DataChangeTriggerStatusValue          enumDataChangeTrigger = 1
	DataChangeTriggerStatusValueTimestamp enumDataChangeTrigger = 2
)

type enumDeadbandType uint32

const (
	DeadbandTypeNone     enumDeadbandType = 0
	DeadbandTypeAbsolute enumDeadbandType = 1
	DeadbandTypePercent  enumDeadbandType = 2
)

type enumRedundancySupport uint32

const (
	RedundancySupportNone           enumRedundancySupport = 0
	RedundancySupportCold           enumRedundancySupport = 1
	RedundancySupportWarm           enumRedundancySupport = 2
	RedundancySupportHot            enumRedundancySupport = 3
	RedundancySupportTransparent    enumRedundancySupport = 4
	RedundancySupportHotAndMirrored enumRedundancySupport = 5
)

type enumServerState uint32

const (
	ServerStateRunning            enumServerState = 0
	ServerStateFailed             enumServerState = 1
	ServerStateNoConfiguration    enumServerState = 2
	ServerStateSuspended          enumServerState = 3
	ServerStateShutdown           enumServerState = 4
	ServerStateTest               enumServerState = 5
	ServerStateCommunicationFault enumServerState = 6
	ServerStateUnknown            enumServerState = 7
)

type enumModelChangeStructureVerbMask uint32

const (
	ModelChangeStructureVerbMaskNodeAdded        enumModelChangeStructureVerbMask = 1
	ModelChangeStructureVerbMaskNodeDeleted      enumModelChangeStructureVerbMask = 2
	ModelChangeStructureVerbMaskReferenceAdded   enumModelChangeStructureVerbMask = 4
	ModelChangeStructureVerbMaskReferenceDeleted enumModelChangeStructureVerbMask = 8
	ModelChangeStructureVerbMaskDataTypeChanged  enumModelChangeStructureVerbMask = 16
)

type enumAxisScaleEnumeration uint32

const (
	AxisScaleEnumerationLinear enumAxisScaleEnumeration = 0
	AxisScaleEnumerationLog    enumAxisScaleEnumeration = 1
	AxisScaleEnumerationLn     enumAxisScaleEnumeration = 2
)

type enumExceptionDeviationFormat uint32

const (
	ExceptionDeviationFormatAbsoluteValue    enumExceptionDeviationFormat = 0
	ExceptionDeviationFormatPercentOfValue   enumExceptionDeviationFormat = 1
	ExceptionDeviationFormatPercentOfRange   enumExceptionDeviationFormat = 2
	ExceptionDeviationFormatPercentOfEURange enumExceptionDeviationFormat = 3
	ExceptionDeviationFormatUnknown          enumExceptionDeviationFormat = 4
)

// XmlElement is an XML element encoded as a UTF-8 string.
type XmlElement struct {
	Length int32
	Value  []rune `opcua:"lengthField=Length"`
}

type TwoByteNodeId struct {
	Identifier uint8
}

type FourByteNodeId struct {
	NamespaceIndex uint8
	Identifier     uint16
}

type NumericNodeId struct {
	NamespaceIndex uint16
	Identifier     uint32
}

type StringNodeId struct {
	NamespaceIndex uint16
	Identifier     string
}

type GuidNodeId struct {
	NamespaceIndex uint16
	Identifier     Guid
}

type ByteStringNodeId struct {
	NamespaceIndex uint16
	Identifier     ByteString
}

// NodeId is an identifier for a node in a UA server address space.
type NodeId struct {
	NodeIdType enumNodeIdType
	Reserved1  byte             `opcua:"bits=2"`
	TwoByte    TwoByteNodeId    `opcua:"switchField=NodeIdType,switchValue=0"`
	FourByte   FourByteNodeId   `opcua:"switchField=NodeIdType,switchValue=1"`
	Numeric    NumericNodeId    `opcua:"switchField=NodeIdType,switchValue=2"`
	String     StringNodeId     `opcua:"switchField=NodeIdType,switchValue=3"`
	Guid       GuidNodeId       `opcua:"switchField=NodeIdType,switchValue=4"`
	ByteString ByteStringNodeId `opcua:"switchField=NodeIdType,switchValue=5"`
}

// ExpandedNodeId is an identifier for a node in a UA server address space qualified with a complete namespace string.
type ExpandedNodeId struct {
	NodeIdType            enumNodeIdType
	ServerIndexSpecified  Bit
	NamespaceURISpecified Bit
	TwoByte               TwoByteNodeId    `opcua:"switchField=NodeIdType,switchValue=0"`
	FourByte              FourByteNodeId   `opcua:"switchField=NodeIdType,switchValue=1"`
	Numeric               NumericNodeId    `opcua:"switchField=NodeIdType,switchValue=2"`
	String                StringNodeId     `opcua:"switchField=NodeIdType,switchValue=3"`
	Guid                  GuidNodeId       `opcua:"switchField=NodeIdType,switchValue=4"`
	ByteString            ByteStringNodeId `opcua:"switchField=NodeIdType,switchValue=5"`
	NamespaceURI          string           `opcua:"switchField=NamespaceURISpecified"`
	ServerIndex           uint32           `opcua:"switchField=ServerIndexSpecified"`
}

// DiagnosticInfo is a recursive structure containing diagnostic information associated with a status code.
type DiagnosticInfo struct {
	SymbolicIdSpecified          Bit
	NamespaceURISpecified        Bit
	LocaleSpecified              Bit
	LocalizedTextSpecified       Bit
	AdditionalInfoSpecified      Bit
	InnerStatusCodeSpecified     Bit
	InnerDiagnosticInfoSpecified Bit
	Reserved1                    byte            `opcua:"bits=2"`
	SymbolicId                   int32           `opcua:"switchField=SymbolicIdSpecified"`
	NamespaceURI                 int32           `opcua:"switchField=NamespaceURISpecified"`
	Locale                       int32           `opcua:"switchField=LocaleSpecified"`
	LocalizedText                int32           `opcua:"switchField=LocalizedTextSpecified"`
	AdditionalInfo               string          `opcua:"switchField=AdditionalInfoSpecified"`
	InnerStatusCode              enumStatusCode  `opcua:"switchField=InnerStatusCodeSpecified"`
	InnerDiagnosticInfo          *DiagnosticInfo `opcua:"switchField=InnerDiagnosticInfoSpecified"`
}

// QualifiedName is a string qualified with a namespace index.
type QualifiedName struct {
	NamespaceIndex int32
	Name           string
}

// LocalizedText is a string qualified with a namespace index.
type LocalizedText struct {
	LocaleSpecified Bit
	TextSpecified   Bit
	Reserved1       byte   `opcua:"bits=6"`
	Locale          string `opcua:"switchField=LocaleSpecified"`
	Text            string `opcua:"switchField=TextSpecified"`
}

// DataValue is a value with an associated timestamp, and quality.
type DataValue struct {
	ValueSpecified             Bit
	StatusCodeSpecified        Bit
	SourceTimestampSpecified   Bit
	SourcePicosecondsSpecified Bit
	ServerTimestampSpecified   Bit
	ServerPicosecondsSpecified Bit
	Reserved1                  byte           `opcua:"bits=2"`
	Value                      Variant        `opcua:"switchField=ValueSpecified"`
	StatusCode                 enumStatusCode `opcua:"switchField=StatusCodeSpecified"`
	SourceTimestamp            time.Time      `opcua:"switchField=SourceTimestampSpecified"`
	SourcePicoseconds          uint16         `opcua:"switchField=SourcePicosecondsSpecified"`
	ServerTimestamp            time.Time      `opcua:"switchField=ServerTimestampSpecified"`
	ServerPicoseconds          uint16         `opcua:"switchField=ServerPicosecondsSpecified"`
}

// ExtensionObject is a serialized object prefixed with its data type identifier.
type ExtensionObject struct {
	TypeIdSpecified Bit
	BinaryBody      Bit
	XmlBody         Bit
	Reserved1       byte           `opcua:"bits=5"`
	TypeId          ExpandedNodeId `opcua:"switchField=TypeIdSpecified"`
	BodyLength      int32
	Body            []uint8 `opcua:"lengthField=BodyLength"`
}

// Variant is a union of several types.
type Variant struct {
	VariantType              byte `opcua:"bits=6"`
	ArrayDimensionsSpecified Bit
	ArrayLengthSpecified     Bit
	ArrayLength              int32             `opcua:"switchField=ArrayLengthSpecified"`
	Boolean                  []bool            `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=1"`
	SByte                    []int8            `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=2"`
	Byte                     []uint8           `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=3"`
	Int16                    []int16           `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=4"`
	UInt16                   []uint16          `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=5"`
	Int32                    []int32           `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=6"`
	UInt32                   []uint32          `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=7"`
	Int64                    []int64           `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=8"`
	UInt64                   []uint64          `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=9"`
	Float                    []float32         `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=10"`
	Double                   []float64         `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=11"`
	String                   []string          `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=12"`
	DateTime                 []time.Time       `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=13"`
	Guid                     []Guid            `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=14"`
	ByteString               []ByteString      `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=15"`
	XmlElement               []XmlElement      `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=16"`
	NodeId                   []NodeId          `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=17"`
	ExpandedNodeId           []ExpandedNodeId  `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=18"`
	StatusCode               []enumStatusCode  `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=19"`
	QualifiedName            []QualifiedName   `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=20"`
	LocalizedText            []LocalizedText   `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=21"`
	ExtensionObject          []ExtensionObject `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=22"`
	DataValue                []DataValue       `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=23"`
	Variant                  []Variant         `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=24"`
	DiagnosticInfo           []DiagnosticInfo  `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=25"`
	NoOfArrayDimensions      int32             `opcua:"switchField=ArrayDimensionsSpecified"`
	ArrayDimensions          []int32           `opcua:"lengthField=NoOfArrayDimensions,switchField=ArrayDimensionsSpecified"`
}

type TrustListDataType struct {
	ExtensionObject

	SpecifiedLists          uint32
	NoOfTrustedCertificates int32
	TrustedCertificates     []ByteString `opcua:"lengthField=NoOfTrustedCertificates"`
	NoOfTrustedCrls         int32
	TrustedCrls             []ByteString `opcua:"lengthField=NoOfTrustedCrls"`
	NoOfIssuerCertificates  int32
	IssuerCertificates      []ByteString `opcua:"lengthField=NoOfIssuerCertificates"`
	NoOfIssuerCrls          int32
	IssuerCrls              []ByteString `opcua:"lengthField=NoOfIssuerCrls"`
}

// Node specifies the attributes which belong to all nodes.
type Node struct {
	ExtensionObject

	NodeId         NodeId
	NodeClass      enumNodeClass
	BrowseName     QualifiedName
	DisplayName    LocalizedText
	Description    LocalizedText
	WriteMask      uint32
	UserWriteMask  uint32
	NoOfReferences int32
	References     []ReferenceNode `opcua:"lengthField=NoOfReferences"`
}

type InstanceNode struct {
	Node

	NodeId         NodeId
	NodeClass      enumNodeClass
	BrowseName     QualifiedName
	DisplayName    LocalizedText
	Description    LocalizedText
	WriteMask      uint32
	UserWriteMask  uint32
	NoOfReferences int32
	References     []ReferenceNode `opcua:"lengthField=NoOfReferences"`
}

type TypeNode struct {
	Node

	NodeId         NodeId
	NodeClass      enumNodeClass
	BrowseName     QualifiedName
	DisplayName    LocalizedText
	Description    LocalizedText
	WriteMask      uint32
	UserWriteMask  uint32
	NoOfReferences int32
	References     []ReferenceNode `opcua:"lengthField=NoOfReferences"`
}

// ObjectNode specifies the attributes which belong to object nodes.
type ObjectNode struct {
	InstanceNode

	NodeId         NodeId
	NodeClass      enumNodeClass
	BrowseName     QualifiedName
	DisplayName    LocalizedText
	Description    LocalizedText
	WriteMask      uint32
	UserWriteMask  uint32
	NoOfReferences int32
	References     []ReferenceNode `opcua:"lengthField=NoOfReferences"`
	EventNotifier  uint8
}

// ObjectTypeNode specifies the attributes which belong to object type nodes.
type ObjectTypeNode struct {
	TypeNode

	NodeId         NodeId
	NodeClass      enumNodeClass
	BrowseName     QualifiedName
	DisplayName    LocalizedText
	Description    LocalizedText
	WriteMask      uint32
	UserWriteMask  uint32
	NoOfReferences int32
	References     []ReferenceNode `opcua:"lengthField=NoOfReferences"`
	IsAbstract     bool
}

// VariableNode specifies the attributes which belong to variable nodes.
type VariableNode struct {
	InstanceNode

	NodeId                  NodeId
	NodeClass               enumNodeClass
	BrowseName              QualifiedName
	DisplayName             LocalizedText
	Description             LocalizedText
	WriteMask               uint32
	UserWriteMask           uint32
	NoOfReferences          int32
	References              []ReferenceNode `opcua:"lengthField=NoOfReferences"`
	Value                   Variant
	DataType                NodeId
	ValueRank               int32
	NoOfArrayDimensions     int32
	ArrayDimensions         []uint32 `opcua:"lengthField=NoOfArrayDimensions"`
	AccessLevel             uint8
	UserAccessLevel         uint8
	MinimumSamplingInterval float64
	Historizing             bool
}

// VariableTypeNode specifies the attributes which belong to variable type nodes.
type VariableTypeNode struct {
	TypeNode

	NodeId              NodeId
	NodeClass           enumNodeClass
	BrowseName          QualifiedName
	DisplayName         LocalizedText
	Description         LocalizedText
	WriteMask           uint32
	UserWriteMask       uint32
	NoOfReferences      int32
	References          []ReferenceNode `opcua:"lengthField=NoOfReferences"`
	Value               Variant
	DataType            NodeId
	ValueRank           int32
	NoOfArrayDimensions int32
	ArrayDimensions     []uint32 `opcua:"lengthField=NoOfArrayDimensions"`
	IsAbstract          bool
}

// ReferenceTypeNode specifies the attributes which belong to reference type nodes.
type ReferenceTypeNode struct {
	TypeNode

	NodeId         NodeId
	NodeClass      enumNodeClass
	BrowseName     QualifiedName
	DisplayName    LocalizedText
	Description    LocalizedText
	WriteMask      uint32
	UserWriteMask  uint32
	NoOfReferences int32
	References     []ReferenceNode `opcua:"lengthField=NoOfReferences"`
	IsAbstract     bool
	Symmetric      bool
	InverseName    LocalizedText
}

// MethodNode specifies the attributes which belong to method nodes.
type MethodNode struct {
	InstanceNode

	NodeId         NodeId
	NodeClass      enumNodeClass
	BrowseName     QualifiedName
	DisplayName    LocalizedText
	Description    LocalizedText
	WriteMask      uint32
	UserWriteMask  uint32
	NoOfReferences int32
	References     []ReferenceNode `opcua:"lengthField=NoOfReferences"`
	Executable     bool
	UserExecutable bool
}

type ViewNode struct {
	InstanceNode

	NodeId          NodeId
	NodeClass       enumNodeClass
	BrowseName      QualifiedName
	DisplayName     LocalizedText
	Description     LocalizedText
	WriteMask       uint32
	UserWriteMask   uint32
	NoOfReferences  int32
	References      []ReferenceNode `opcua:"lengthField=NoOfReferences"`
	ContainsNoLoops bool
	EventNotifier   uint8
}

type DataTypeNode struct {
	TypeNode

	NodeId         NodeId
	NodeClass      enumNodeClass
	BrowseName     QualifiedName
	DisplayName    LocalizedText
	Description    LocalizedText
	WriteMask      uint32
	UserWriteMask  uint32
	NoOfReferences int32
	References     []ReferenceNode `opcua:"lengthField=NoOfReferences"`
	IsAbstract     bool
}

// ReferenceNode specifies a reference which belongs to a node.
type ReferenceNode struct {
	ExtensionObject

	ReferenceTypeId NodeId
	IsInverse       bool
	TargetId        ExpandedNodeId
}

// Argument is an argument for a method.
type Argument struct {
	ExtensionObject

	Name                String
	DataType            NodeId
	ValueRank           int32
	NoOfArrayDimensions int32
	ArrayDimensions     []uint32 `opcua:"lengthField=NoOfArrayDimensions"`
	Description         LocalizedText
}

// EnumValueType is a mapping between a value of an enumerated type and a name and description.
type EnumValueType struct {
	ExtensionObject

	Value       int64
	DisplayName LocalizedText
	Description LocalizedText
}

// OptionSet this abstract Structured DataType is the base DataType for all DataTypes representing a bit mask.
type OptionSet struct {
	ExtensionObject

	Value     ByteString
	ValidBits ByteString
}

// Union this abstract DataType is the base DataType for all union DataTypes.
type Union struct {
	ExtensionObject
}

type TimeZoneDataType struct {
	ExtensionObject

	Offset                 int16
	DaylightSavingInOffset bool
}

// ApplicationDescription describes an application and how to find it.
type ApplicationDescription struct {
	ExtensionObject

	ApplicationUri      String
	ProductUri          String
	ApplicationName     LocalizedText
	ApplicationType     enumApplicationType
	GatewayServerUri    String
	DiscoveryProfileUri String
	NoOfDiscoveryUrls   int32
	DiscoveryUrls       []String `opcua:"lengthField=NoOfDiscoveryUrls"`
}

// RequestHeader the header passed with every server request.
type RequestHeader struct {
	ExtensionObject

	AuthenticationToken NodeId
	Timestamp           time.Time
	RequestHandle       uint32
	ReturnDiagnostics   uint32
	AuditEntryId        String
	TimeoutHint         uint32
	AdditionalHeader    ExtensionObject
}

// ResponseHeader the header passed with every server response.
type ResponseHeader struct {
	ExtensionObject

	Timestamp          time.Time
	RequestHandle      uint32
	ServiceResult      enumStatusCode
	ServiceDiagnostics *DiagnosticInfo
	NoOfStringTable    int32
	StringTable        []String `opcua:"lengthField=NoOfStringTable"`
	AdditionalHeader   ExtensionObject
}

// ServiceFault the response returned by all services when there is a service level error.
type ServiceFault struct {
	ExtensionObject

	ResponseHeader ResponseHeader
}

// FindServersRequest finds the servers known to the discovery server.
type FindServersRequest struct {
	ExtensionObject

	RequestHeader  RequestHeader
	EndpointUrl    String
	NoOfLocaleIds  int32
	LocaleIds      []String `opcua:"lengthField=NoOfLocaleIds"`
	NoOfServerUris int32
	ServerUris     []String `opcua:"lengthField=NoOfServerUris"`
}

// FindServersResponse finds the servers known to the discovery server.
type FindServersResponse struct {
	ExtensionObject

	ResponseHeader ResponseHeader
	NoOfServers    int32
	Servers        []ApplicationDescription `opcua:"lengthField=NoOfServers"`
}

type ServerOnNetwork struct {
	ExtensionObject

	RecordId               uint32
	ServerName             String
	DiscoveryUrl           String
	NoOfServerCapabilities int32
	ServerCapabilities     []String `opcua:"lengthField=NoOfServerCapabilities"`
}

type FindServersOnNetworkRequest struct {
	ExtensionObject

	RequestHeader              RequestHeader
	StartingRecordId           uint32
	MaxRecordsToReturn         uint32
	NoOfServerCapabilityFilter int32
	ServerCapabilityFilter     []String `opcua:"lengthField=NoOfServerCapabilityFilter"`
}

type FindServersOnNetworkResponse struct {
	ExtensionObject

	ResponseHeader       ResponseHeader
	LastCounterResetTime time.Time
	NoOfServers          int32
	Servers              []ServerOnNetwork `opcua:"lengthField=NoOfServers"`
}

// UserTokenPolicy describes a user token that can be used with a server.
type UserTokenPolicy struct {
	ExtensionObject

	PolicyId          String
	TokenType         enumUserTokenType
	IssuedTokenType   String
	IssuerEndpointUrl String
	SecurityPolicyUri String
}

// EndpointDescription the description of a endpoint that can be used to access a server.
type EndpointDescription struct {
	ExtensionObject

	EndpointUrl            String
	Server                 ApplicationDescription
	ServerCertificate      ByteString
	SecurityMode           enumMessageSecurityMode
	SecurityPolicyUri      String
	NoOfUserIdentityTokens int32
	UserIdentityTokens     []UserTokenPolicy `opcua:"lengthField=NoOfUserIdentityTokens"`
	TransportProfileUri    String
	SecurityLevel          uint8
}

// GetEndpointsRequest gets the endpoints used by the server.
type GetEndpointsRequest struct {
	ExtensionObject

	RequestHeader   RequestHeader
	EndpointUrl     String
	NoOfLocaleIds   int32
	LocaleIds       []String `opcua:"lengthField=NoOfLocaleIds"`
	NoOfProfileUris int32
	ProfileUris     []String `opcua:"lengthField=NoOfProfileUris"`
}

// GetEndpointsResponse gets the endpoints used by the server.
type GetEndpointsResponse struct {
	ExtensionObject

	ResponseHeader ResponseHeader
	NoOfEndpoints  int32
	Endpoints      []EndpointDescription `opcua:"lengthField=NoOfEndpoints"`
}

// RegisteredServer the information required to register a server with a discovery server.
type RegisteredServer struct {
	ExtensionObject

	ServerUri         String
	ProductUri        String
	NoOfServerNames   int32
	ServerNames       []LocalizedText `opcua:"lengthField=NoOfServerNames"`
	ServerType        enumApplicationType
	GatewayServerUri  String
	NoOfDiscoveryUrls int32
	DiscoveryUrls     []String `opcua:"lengthField=NoOfDiscoveryUrls"`
	SemaphoreFilePath String
	IsOnline          bool
}

// RegisterServerRequest registers a server with the discovery server.
type RegisterServerRequest struct {
	ExtensionObject

	RequestHeader RequestHeader
	Server        RegisteredServer
}

// RegisterServerResponse registers a server with the discovery server.
type RegisterServerResponse struct {
	ExtensionObject

	ResponseHeader ResponseHeader
}

// DiscoveryConfiguration is a base type for discovery configuration information.
type DiscoveryConfiguration struct {
	ExtensionObject
}

// MdnsDiscoveryConfiguration the discovery information needed for mDNS registration.
type MdnsDiscoveryConfiguration struct {
	DiscoveryConfiguration

	MdnsServerName         String
	NoOfServerCapabilities int32
	ServerCapabilities     []String `opcua:"lengthField=NoOfServerCapabilities"`
}

type RegisterServer2Request struct {
	ExtensionObject

	RequestHeader              RequestHeader
	Server                     RegisteredServer
	NoOfDiscoveryConfiguration int32
	DiscoveryConfiguration     []ExtensionObject `opcua:"lengthField=NoOfDiscoveryConfiguration"`
}

type RegisterServer2Response struct {
	ExtensionObject

	ResponseHeader           ResponseHeader
	NoOfConfigurationResults int32
	ConfigurationResults     []enumStatusCode `opcua:"lengthField=NoOfConfigurationResults"`
	NoOfDiagnosticInfos      int32
	DiagnosticInfos          []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

// ChannelSecurityToken the token that identifies a set of keys for an active secure channel.
type ChannelSecurityToken struct {
	ExtensionObject

	ChannelId       uint32
	TokenId         uint32
	CreatedAt       time.Time
	RevisedLifetime uint32
}

// OpenSecureChannelRequest creates a secure channel with a server.
type OpenSecureChannelRequest struct {
	ExtensionObject

	RequestHeader         RequestHeader
	ClientProtocolVersion uint32
	RequestType           enumSecurityTokenRequestType
	SecurityMode          enumMessageSecurityMode
	ClientNonce           ByteString
	RequestedLifetime     uint32
}

// OpenSecureChannelResponse creates a secure channel with a server.
type OpenSecureChannelResponse struct {
	ExtensionObject

	ResponseHeader        ResponseHeader
	ServerProtocolVersion uint32
	SecurityToken         ChannelSecurityToken
	ServerNonce           ByteString
}

// CloseSecureChannelRequest closes a secure channel.
type CloseSecureChannelRequest struct {
	ExtensionObject

	RequestHeader RequestHeader
}

// CloseSecureChannelResponse closes a secure channel.
type CloseSecureChannelResponse struct {
	ExtensionObject

	ResponseHeader ResponseHeader
}

// SignedSoftwareCertificate is a software certificate with a digital signature.
type SignedSoftwareCertificate struct {
	ExtensionObject

	CertificateData ByteString
	Signature       ByteString
}

// SignatureData is a digital signature.
type SignatureData struct {
	ExtensionObject

	Algorithm String
	Signature ByteString
}

// CreateSessionRequest creates a new session with the server.
type CreateSessionRequest struct {
	ExtensionObject

	RequestHeader           RequestHeader
	ClientDescription       ApplicationDescription
	ServerUri               String
	EndpointUrl             String
	SessionName             String
	ClientNonce             ByteString
	ClientCertificate       ByteString
	RequestedSessionTimeout float64
	MaxResponseMessageSize  uint32
}

// CreateSessionResponse creates a new session with the server.
type CreateSessionResponse struct {
	ExtensionObject

	ResponseHeader                 ResponseHeader
	SessionId                      NodeId
	AuthenticationToken            NodeId
	RevisedSessionTimeout          float64
	ServerNonce                    ByteString
	ServerCertificate              ByteString
	NoOfServerEndpoints            int32
	ServerEndpoints                []EndpointDescription `opcua:"lengthField=NoOfServerEndpoints"`
	NoOfServerSoftwareCertificates int32
	ServerSoftwareCertificates     []SignedSoftwareCertificate `opcua:"lengthField=NoOfServerSoftwareCertificates"`
	ServerSignature                SignatureData
	MaxRequestMessageSize          uint32
}

// UserIdentityToken is a base type for a user identity token.
type UserIdentityToken struct {
	ExtensionObject

	PolicyId String
}

// AnonymousIdentityToken is a token representing an anonymous user.
type AnonymousIdentityToken struct {
	UserIdentityToken

	PolicyId String
}

// UserNameIdentityToken is a token representing a user identified by a user name and password.
type UserNameIdentityToken struct {
	UserIdentityToken

	PolicyId            String
	UserName            String
	Password            ByteString
	EncryptionAlgorithm String
}

// X509IdentityToken is a token representing a user identified by an X509 certificate.
type X509IdentityToken struct {
	UserIdentityToken

	PolicyId        String
	CertificateData ByteString
}

// IssuedIdentityToken is a token representing a user identified by a WS-Security XML token.
type IssuedIdentityToken struct {
	UserIdentityToken

	PolicyId            String
	TokenData           ByteString
	EncryptionAlgorithm String
}

// ActivateSessionRequest activates a session with the server.
type ActivateSessionRequest struct {
	ExtensionObject

	RequestHeader                  RequestHeader
	ClientSignature                SignatureData
	NoOfClientSoftwareCertificates int32
	ClientSoftwareCertificates     []SignedSoftwareCertificate `opcua:"lengthField=NoOfClientSoftwareCertificates"`
	NoOfLocaleIds                  int32
	LocaleIds                      []String `opcua:"lengthField=NoOfLocaleIds"`
	UserIdentityToken              ExtensionObject
	UserTokenSignature             SignatureData
}

// ActivateSessionResponse activates a session with the server.
type ActivateSessionResponse struct {
	ExtensionObject

	ResponseHeader      ResponseHeader
	ServerNonce         ByteString
	NoOfResults         int32
	Results             []enumStatusCode `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

// CloseSessionRequest closes a session with the server.
type CloseSessionRequest struct {
	ExtensionObject

	RequestHeader       RequestHeader
	DeleteSubscriptions bool
}

// CloseSessionResponse closes a session with the server.
type CloseSessionResponse struct {
	ExtensionObject

	ResponseHeader ResponseHeader
}

// CancelRequest cancels an outstanding request.
type CancelRequest struct {
	ExtensionObject

	RequestHeader RequestHeader
	RequestHandle uint32
}

// CancelResponse cancels an outstanding request.
type CancelResponse struct {
	ExtensionObject

	ResponseHeader ResponseHeader
	CancelCount    uint32
}

// NodeAttributes the base attributes for all nodes.
type NodeAttributes struct {
	ExtensionObject

	SpecifiedAttributes uint32
	DisplayName         LocalizedText
	Description         LocalizedText
	WriteMask           uint32
	UserWriteMask       uint32
}

// ObjectAttributes the attributes for an object node.
type ObjectAttributes struct {
	NodeAttributes

	SpecifiedAttributes uint32
	DisplayName         LocalizedText
	Description         LocalizedText
	WriteMask           uint32
	UserWriteMask       uint32
	EventNotifier       uint8
}

// VariableAttributes the attributes for a variable node.
type VariableAttributes struct {
	NodeAttributes

	SpecifiedAttributes     uint32
	DisplayName             LocalizedText
	Description             LocalizedText
	WriteMask               uint32
	UserWriteMask           uint32
	Value                   Variant
	DataType                NodeId
	ValueRank               int32
	NoOfArrayDimensions     int32
	ArrayDimensions         []uint32 `opcua:"lengthField=NoOfArrayDimensions"`
	AccessLevel             uint8
	UserAccessLevel         uint8
	MinimumSamplingInterval float64
	Historizing             bool
}

// MethodAttributes the attributes for a method node.
type MethodAttributes struct {
	NodeAttributes

	SpecifiedAttributes uint32
	DisplayName         LocalizedText
	Description         LocalizedText
	WriteMask           uint32
	UserWriteMask       uint32
	Executable          bool
	UserExecutable      bool
}

// ObjectTypeAttributes the attributes for an object type node.
type ObjectTypeAttributes struct {
	NodeAttributes

	SpecifiedAttributes uint32
	DisplayName         LocalizedText
	Description         LocalizedText
	WriteMask           uint32
	UserWriteMask       uint32
	IsAbstract          bool
}

// VariableTypeAttributes the attributes for a variable type node.
type VariableTypeAttributes struct {
	NodeAttributes

	SpecifiedAttributes uint32
	DisplayName         LocalizedText
	Description         LocalizedText
	WriteMask           uint32
	UserWriteMask       uint32
	Value               Variant
	DataType            NodeId
	ValueRank           int32
	NoOfArrayDimensions int32
	ArrayDimensions     []uint32 `opcua:"lengthField=NoOfArrayDimensions"`
	IsAbstract          bool
}

// ReferenceTypeAttributes the attributes for a reference type node.
type ReferenceTypeAttributes struct {
	NodeAttributes

	SpecifiedAttributes uint32
	DisplayName         LocalizedText
	Description         LocalizedText
	WriteMask           uint32
	UserWriteMask       uint32
	IsAbstract          bool
	Symmetric           bool
	InverseName         LocalizedText
}

// DataTypeAttributes the attributes for a data type node.
type DataTypeAttributes struct {
	NodeAttributes

	SpecifiedAttributes uint32
	DisplayName         LocalizedText
	Description         LocalizedText
	WriteMask           uint32
	UserWriteMask       uint32
	IsAbstract          bool
}

// ViewAttributes the attributes for a view node.
type ViewAttributes struct {
	NodeAttributes

	SpecifiedAttributes uint32
	DisplayName         LocalizedText
	Description         LocalizedText
	WriteMask           uint32
	UserWriteMask       uint32
	ContainsNoLoops     bool
	EventNotifier       uint8
}

// AddNodesItem is a request to add a node to the server address space.
type AddNodesItem struct {
	ExtensionObject

	ParentNodeId       ExpandedNodeId
	ReferenceTypeId    NodeId
	RequestedNewNodeId ExpandedNodeId
	BrowseName         QualifiedName
	NodeClass          enumNodeClass
	NodeAttributes     ExtensionObject
	TypeDefinition     ExpandedNodeId
}

// AddNodesResult is a result of an add node operation.
type AddNodesResult struct {
	ExtensionObject

	StatusCode  enumStatusCode
	AddedNodeId NodeId
}

// AddNodesRequest adds one or more nodes to the server address space.
type AddNodesRequest struct {
	ExtensionObject

	RequestHeader  RequestHeader
	NoOfNodesToAdd int32
	NodesToAdd     []AddNodesItem `opcua:"lengthField=NoOfNodesToAdd"`
}

// AddNodesResponse adds one or more nodes to the server address space.
type AddNodesResponse struct {
	ExtensionObject

	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []AddNodesResult `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

// AddReferencesItem is a request to add a reference to the server address space.
type AddReferencesItem struct {
	ExtensionObject

	SourceNodeId    NodeId
	ReferenceTypeId NodeId
	IsForward       bool
	TargetServerUri String
	TargetNodeId    ExpandedNodeId
	TargetNodeClass enumNodeClass
}

// AddReferencesRequest adds one or more references to the server address space.
type AddReferencesRequest struct {
	ExtensionObject

	RequestHeader       RequestHeader
	NoOfReferencesToAdd int32
	ReferencesToAdd     []AddReferencesItem `opcua:"lengthField=NoOfReferencesToAdd"`
}

// AddReferencesResponse adds one or more references to the server address space.
type AddReferencesResponse struct {
	ExtensionObject

	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []enumStatusCode `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

// DeleteNodesItem is a request to delete a node to the server address space.
type DeleteNodesItem struct {
	ExtensionObject

	NodeId                 NodeId
	DeleteTargetReferences bool
}

// DeleteNodesRequest delete one or more nodes from the server address space.
type DeleteNodesRequest struct {
	ExtensionObject

	RequestHeader     RequestHeader
	NoOfNodesToDelete int32
	NodesToDelete     []DeleteNodesItem `opcua:"lengthField=NoOfNodesToDelete"`
}

// DeleteNodesResponse delete one or more nodes from the server address space.
type DeleteNodesResponse struct {
	ExtensionObject

	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []enumStatusCode `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

// DeleteReferencesItem is a request to delete a node from the server address space.
type DeleteReferencesItem struct {
	ExtensionObject

	SourceNodeId        NodeId
	ReferenceTypeId     NodeId
	IsForward           bool
	TargetNodeId        ExpandedNodeId
	DeleteBidirectional bool
}

// DeleteReferencesRequest delete one or more references from the server address space.
type DeleteReferencesRequest struct {
	ExtensionObject

	RequestHeader          RequestHeader
	NoOfReferencesToDelete int32
	ReferencesToDelete     []DeleteReferencesItem `opcua:"lengthField=NoOfReferencesToDelete"`
}

// DeleteReferencesResponse delete one or more references from the server address space.
type DeleteReferencesResponse struct {
	ExtensionObject

	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []enumStatusCode `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

// ViewDescription the view to browse.
type ViewDescription struct {
	ExtensionObject

	ViewId      NodeId
	Timestamp   time.Time
	ViewVersion uint32
}

// BrowseDescription is a request to browse the the references from a node.
type BrowseDescription struct {
	ExtensionObject

	NodeId          NodeId
	BrowseDirection enumBrowseDirection
	ReferenceTypeId NodeId
	IncludeSubtypes bool
	NodeClassMask   uint32
	ResultMask      uint32
}

// ReferenceDescription the description of a reference.
type ReferenceDescription struct {
	ExtensionObject

	ReferenceTypeId NodeId
	IsForward       bool
	NodeId          ExpandedNodeId
	BrowseName      QualifiedName
	DisplayName     LocalizedText
	NodeClass       enumNodeClass
	TypeDefinition  ExpandedNodeId
}

// BrowseResult the result of a browse operation.
type BrowseResult struct {
	ExtensionObject

	StatusCode        enumStatusCode
	ContinuationPoint ByteString
	NoOfReferences    int32
	References        []ReferenceDescription `opcua:"lengthField=NoOfReferences"`
}

// BrowseRequest browse the references for one or more nodes from the server address space.
type BrowseRequest struct {
	ExtensionObject

	RequestHeader                 RequestHeader
	View                          ViewDescription
	RequestedMaxReferencesPerNode uint32
	NoOfNodesToBrowse             int32
	NodesToBrowse                 []BrowseDescription `opcua:"lengthField=NoOfNodesToBrowse"`
}

// BrowseResponse browse the references for one or more nodes from the server address space.
type BrowseResponse struct {
	ExtensionObject

	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []BrowseResult `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

// BrowseNextRequest continues one or more browse operations.
type BrowseNextRequest struct {
	ExtensionObject

	RequestHeader             RequestHeader
	ReleaseContinuationPoints bool
	NoOfContinuationPoints    int32
	ContinuationPoints        []ByteString `opcua:"lengthField=NoOfContinuationPoints"`
}

// BrowseNextResponse continues one or more browse operations.
type BrowseNextResponse struct {
	ExtensionObject

	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []BrowseResult `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

// RelativePathElement is an element in a relative path.
type RelativePathElement struct {
	ExtensionObject

	ReferenceTypeId NodeId
	IsInverse       bool
	IncludeSubtypes bool
	TargetName      QualifiedName
}

// RelativePath is a relative path constructed from reference types and browse names.
type RelativePath struct {
	ExtensionObject

	NoOfElements int32
	Elements     []RelativePathElement `opcua:"lengthField=NoOfElements"`
}

// BrowsePath is a request to translate a path into a node id.
type BrowsePath struct {
	ExtensionObject

	StartingNode NodeId
	RelativePath RelativePath
}

// BrowsePathTarget the target of the translated path.
type BrowsePathTarget struct {
	ExtensionObject

	TargetId           ExpandedNodeId
	RemainingPathIndex uint32
}

// BrowsePathResult the result of a translate opearation.
type BrowsePathResult struct {
	ExtensionObject

	StatusCode  enumStatusCode
	NoOfTargets int32
	Targets     []BrowsePathTarget `opcua:"lengthField=NoOfTargets"`
}

// TranslateBrowsePathsToNodeIdsRequest translates one or more paths in the server address space.
type TranslateBrowsePathsToNodeIdsRequest struct {
	ExtensionObject

	RequestHeader   RequestHeader
	NoOfBrowsePaths int32
	BrowsePaths     []BrowsePath `opcua:"lengthField=NoOfBrowsePaths"`
}

// TranslateBrowsePathsToNodeIdsResponse translates one or more paths in the server address space.
type TranslateBrowsePathsToNodeIdsResponse struct {
	ExtensionObject

	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []BrowsePathResult `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

// RegisterNodesRequest registers one or more nodes for repeated use within a session.
type RegisterNodesRequest struct {
	ExtensionObject

	RequestHeader       RequestHeader
	NoOfNodesToRegister int32
	NodesToRegister     []NodeId `opcua:"lengthField=NoOfNodesToRegister"`
}

// RegisterNodesResponse registers one or more nodes for repeated use within a session.
type RegisterNodesResponse struct {
	ExtensionObject

	ResponseHeader        ResponseHeader
	NoOfRegisteredNodeIds int32
	RegisteredNodeIds     []NodeId `opcua:"lengthField=NoOfRegisteredNodeIds"`
}

// UnregisterNodesRequest unregisters one or more previously registered nodes.
type UnregisterNodesRequest struct {
	ExtensionObject

	RequestHeader         RequestHeader
	NoOfNodesToUnregister int32
	NodesToUnregister     []NodeId `opcua:"lengthField=NoOfNodesToUnregister"`
}

// UnregisterNodesResponse unregisters one or more previously registered nodes.
type UnregisterNodesResponse struct {
	ExtensionObject

	ResponseHeader ResponseHeader
}

type EndpointConfiguration struct {
	ExtensionObject

	OperationTimeout      int32
	UseBinaryEncoding     bool
	MaxStringLength       int32
	MaxByteStringLength   int32
	MaxArrayLength        int32
	MaxMessageSize        int32
	MaxBufferSize         int32
	ChannelLifetime       int32
	SecurityTokenLifetime int32
}

type QueryDataDescription struct {
	ExtensionObject

	RelativePath RelativePath
	AttributeId  uint32
	IndexRange   String
}

type NodeTypeDescription struct {
	ExtensionObject

	TypeDefinitionNode ExpandedNodeId
	IncludeSubTypes    bool
	NoOfDataToReturn   int32
	DataToReturn       []QueryDataDescription `opcua:"lengthField=NoOfDataToReturn"`
}

type QueryDataSet struct {
	ExtensionObject

	NodeId             ExpandedNodeId
	TypeDefinitionNode ExpandedNodeId
	NoOfValues         int32
	Values             []Variant `opcua:"lengthField=NoOfValues"`
}

type NodeReference struct {
	ExtensionObject

	NodeId                NodeId
	ReferenceTypeId       NodeId
	IsForward             bool
	NoOfReferencedNodeIds int32
	ReferencedNodeIds     []NodeId `opcua:"lengthField=NoOfReferencedNodeIds"`
}

type ContentFilterElement struct {
	ExtensionObject

	FilterOperator     enumFilterOperator
	NoOfFilterOperands int32
	FilterOperands     []ExtensionObject `opcua:"lengthField=NoOfFilterOperands"`
}

type ContentFilter struct {
	ExtensionObject

	NoOfElements int32
	Elements     []ContentFilterElement `opcua:"lengthField=NoOfElements"`
}

type FilterOperand struct {
	ExtensionObject
}

type ElementOperand struct {
	FilterOperand

	Index uint32
}

type LiteralOperand struct {
	FilterOperand

	Value Variant
}

type AttributeOperand struct {
	FilterOperand

	NodeId      NodeId
	Alias       String
	BrowsePath  RelativePath
	AttributeId uint32
	IndexRange  String
}

type SimpleAttributeOperand struct {
	FilterOperand

	TypeDefinitionId NodeId
	NoOfBrowsePath   int32
	BrowsePath       []QualifiedName `opcua:"lengthField=NoOfBrowsePath"`
	AttributeId      uint32
	IndexRange       String
}

type ContentFilterElementResult struct {
	ExtensionObject

	StatusCode                 enumStatusCode
	NoOfOperandStatusCodes     int32
	OperandStatusCodes         []enumStatusCode `opcua:"lengthField=NoOfOperandStatusCodes"`
	NoOfOperandDiagnosticInfos int32
	OperandDiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfOperandDiagnosticInfos"`
}

type ContentFilterResult struct {
	ExtensionObject

	NoOfElementResults         int32
	ElementResults             []ContentFilterElementResult `opcua:"lengthField=NoOfElementResults"`
	NoOfElementDiagnosticInfos int32
	ElementDiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfElementDiagnosticInfos"`
}

type ParsingResult struct {
	ExtensionObject

	StatusCode              enumStatusCode
	NoOfDataStatusCodes     int32
	DataStatusCodes         []enumStatusCode `opcua:"lengthField=NoOfDataStatusCodes"`
	NoOfDataDiagnosticInfos int32
	DataDiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDataDiagnosticInfos"`
}

type QueryFirstRequest struct {
	ExtensionObject

	RequestHeader         RequestHeader
	View                  ViewDescription
	NoOfNodeTypes         int32
	NodeTypes             []NodeTypeDescription `opcua:"lengthField=NoOfNodeTypes"`
	Filter                ContentFilter
	MaxDataSetsToReturn   uint32
	MaxReferencesToReturn uint32
}

type QueryFirstResponse struct {
	ExtensionObject

	ResponseHeader      ResponseHeader
	NoOfQueryDataSets   int32
	QueryDataSets       []QueryDataSet `opcua:"lengthField=NoOfQueryDataSets"`
	ContinuationPoint   ByteString
	NoOfParsingResults  int32
	ParsingResults      []ParsingResult `opcua:"lengthField=NoOfParsingResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
	FilterResult        ContentFilterResult
}

type QueryNextRequest struct {
	ExtensionObject

	RequestHeader            RequestHeader
	ReleaseContinuationPoint bool
	ContinuationPoint        ByteString
}

type QueryNextResponse struct {
	ExtensionObject

	ResponseHeader           ResponseHeader
	NoOfQueryDataSets        int32
	QueryDataSets            []QueryDataSet `opcua:"lengthField=NoOfQueryDataSets"`
	RevisedContinuationPoint ByteString
}

type ReadValueId struct {
	ExtensionObject

	NodeId       NodeId
	AttributeId  uint32
	IndexRange   String
	DataEncoding QualifiedName
}

type ReadRequest struct {
	ExtensionObject

	RequestHeader      RequestHeader
	MaxAge             float64
	TimestampsToReturn enumTimestampsToReturn
	NoOfNodesToRead    int32
	NodesToRead        []ReadValueId `opcua:"lengthField=NoOfNodesToRead"`
}

type ReadResponse struct {
	ExtensionObject

	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []DataValue `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type HistoryReadValueId struct {
	ExtensionObject

	NodeId            NodeId
	IndexRange        String
	DataEncoding      QualifiedName
	ContinuationPoint ByteString
}

type HistoryReadResult struct {
	ExtensionObject

	StatusCode        enumStatusCode
	ContinuationPoint ByteString
	HistoryData       ExtensionObject
}

type HistoryReadDetails struct {
	ExtensionObject
}

type ReadEventDetails struct {
	HistoryReadDetails

	NumValuesPerNode uint32
	StartTime        time.Time
	EndTime          time.Time
	Filter           EventFilter
}

type ReadRawModifiedDetails struct {
	HistoryReadDetails

	IsReadModified   bool
	StartTime        time.Time
	EndTime          time.Time
	NumValuesPerNode uint32
	ReturnBounds     bool
}

type ReadProcessedDetails struct {
	HistoryReadDetails

	StartTime              time.Time
	EndTime                time.Time
	ProcessingInterval     float64
	NoOfAggregateType      int32
	AggregateType          []NodeId `opcua:"lengthField=NoOfAggregateType"`
	AggregateConfiguration AggregateConfiguration
}

type ReadAtTimeDetails struct {
	HistoryReadDetails

	NoOfReqTimes    int32
	ReqTimes        []time.Time `opcua:"lengthField=NoOfReqTimes"`
	UseSimpleBounds bool
}

type HistoryData struct {
	ExtensionObject

	NoOfDataValues int32
	DataValues     []DataValue `opcua:"lengthField=NoOfDataValues"`
}

type ModificationInfo struct {
	ExtensionObject

	ModificationTime time.Time
	UpdateType       enumHistoryUpdateType
	UserName         String
}

type HistoryModifiedData struct {
	HistoryData

	NoOfDataValues        int32
	DataValues            []DataValue `opcua:"lengthField=NoOfDataValues"`
	NoOfModificationInfos int32
	ModificationInfos     []ModificationInfo `opcua:"lengthField=NoOfModificationInfos"`
}

type HistoryEvent struct {
	ExtensionObject

	NoOfEvents int32
	Events     []HistoryEventFieldList `opcua:"lengthField=NoOfEvents"`
}

type HistoryReadRequest struct {
	ExtensionObject

	RequestHeader             RequestHeader
	HistoryReadDetails        ExtensionObject
	TimestampsToReturn        enumTimestampsToReturn
	ReleaseContinuationPoints bool
	NoOfNodesToRead           int32
	NodesToRead               []HistoryReadValueId `opcua:"lengthField=NoOfNodesToRead"`
}

type HistoryReadResponse struct {
	ExtensionObject

	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []HistoryReadResult `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type WriteValue struct {
	ExtensionObject

	NodeId      NodeId
	AttributeId uint32
	IndexRange  String
	Value       DataValue
}

type WriteRequest struct {
	ExtensionObject

	RequestHeader    RequestHeader
	NoOfNodesToWrite int32
	NodesToWrite     []WriteValue `opcua:"lengthField=NoOfNodesToWrite"`
}

type WriteResponse struct {
	ExtensionObject

	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []enumStatusCode `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type HistoryUpdateDetails struct {
	ExtensionObject

	NodeId NodeId
}

type UpdateDataDetails struct {
	HistoryUpdateDetails

	NodeId               NodeId
	PerformInsertReplace enumPerformUpdateType
	NoOfUpdateValues     int32
	UpdateValues         []DataValue `opcua:"lengthField=NoOfUpdateValues"`
}

type UpdateStructureDataDetails struct {
	HistoryUpdateDetails

	NodeId               NodeId
	PerformInsertReplace enumPerformUpdateType
	NoOfUpdateValues     int32
	UpdateValues         []DataValue `opcua:"lengthField=NoOfUpdateValues"`
}

type UpdateEventDetails struct {
	HistoryUpdateDetails

	NodeId               NodeId
	PerformInsertReplace enumPerformUpdateType
	Filter               EventFilter
	NoOfEventData        int32
	EventData            []HistoryEventFieldList `opcua:"lengthField=NoOfEventData"`
}

type DeleteRawModifiedDetails struct {
	HistoryUpdateDetails

	NodeId           NodeId
	IsDeleteModified bool
	StartTime        time.Time
	EndTime          time.Time
}

type DeleteAtTimeDetails struct {
	HistoryUpdateDetails

	NodeId       NodeId
	NoOfReqTimes int32
	ReqTimes     []time.Time `opcua:"lengthField=NoOfReqTimes"`
}

type DeleteEventDetails struct {
	HistoryUpdateDetails

	NodeId       NodeId
	NoOfEventIds int32
	EventIds     []ByteString `opcua:"lengthField=NoOfEventIds"`
}

type HistoryUpdateResult struct {
	ExtensionObject

	StatusCode           enumStatusCode
	NoOfOperationResults int32
	OperationResults     []enumStatusCode `opcua:"lengthField=NoOfOperationResults"`
	NoOfDiagnosticInfos  int32
	DiagnosticInfos      []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type HistoryUpdateRequest struct {
	ExtensionObject

	RequestHeader            RequestHeader
	NoOfHistoryUpdateDetails int32
	HistoryUpdateDetails     []ExtensionObject `opcua:"lengthField=NoOfHistoryUpdateDetails"`
}

type HistoryUpdateResponse struct {
	ExtensionObject

	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []HistoryUpdateResult `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type CallMethodRequest struct {
	ExtensionObject

	ObjectId           NodeId
	MethodId           NodeId
	NoOfInputArguments int32
	InputArguments     []Variant `opcua:"lengthField=NoOfInputArguments"`
}

type CallMethodResult struct {
	ExtensionObject

	StatusCode                       enumStatusCode
	NoOfInputArgumentResults         int32
	InputArgumentResults             []enumStatusCode `opcua:"lengthField=NoOfInputArgumentResults"`
	NoOfInputArgumentDiagnosticInfos int32
	InputArgumentDiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfInputArgumentDiagnosticInfos"`
	NoOfOutputArguments              int32
	OutputArguments                  []Variant `opcua:"lengthField=NoOfOutputArguments"`
}

type CallRequest struct {
	ExtensionObject

	RequestHeader     RequestHeader
	NoOfMethodsToCall int32
	MethodsToCall     []CallMethodRequest `opcua:"lengthField=NoOfMethodsToCall"`
}

type CallResponse struct {
	ExtensionObject

	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []CallMethodResult `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type MonitoringFilter struct {
	ExtensionObject
}

type DataChangeFilter struct {
	MonitoringFilter

	Trigger       enumDataChangeTrigger
	DeadbandType  uint32
	DeadbandValue float64
}

type EventFilter struct {
	MonitoringFilter

	NoOfSelectClauses int32
	SelectClauses     []SimpleAttributeOperand `opcua:"lengthField=NoOfSelectClauses"`
	WhereClause       ContentFilter
}

type AggregateConfiguration struct {
	ExtensionObject

	UseServerCapabilitiesDefaults bool
	TreatUncertainAsBad           bool
	PercentDataBad                uint8
	PercentDataGood               uint8
	UseSlopedExtrapolation        bool
}

type AggregateFilter struct {
	MonitoringFilter

	StartTime              time.Time
	AggregateType          NodeId
	ProcessingInterval     float64
	AggregateConfiguration AggregateConfiguration
}

type MonitoringFilterResult struct {
	ExtensionObject
}

type EventFilterResult struct {
	MonitoringFilterResult

	NoOfSelectClauseResults         int32
	SelectClauseResults             []enumStatusCode `opcua:"lengthField=NoOfSelectClauseResults"`
	NoOfSelectClauseDiagnosticInfos int32
	SelectClauseDiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfSelectClauseDiagnosticInfos"`
	WhereClauseResult               ContentFilterResult
}

type AggregateFilterResult struct {
	MonitoringFilterResult

	RevisedStartTime              time.Time
	RevisedProcessingInterval     float64
	RevisedAggregateConfiguration AggregateConfiguration
}

type MonitoringParameters struct {
	ExtensionObject

	ClientHandle     uint32
	SamplingInterval float64
	Filter           ExtensionObject
	QueueSize        uint32
	DiscardOldest    bool
}

type MonitoredItemCreateRequest struct {
	ExtensionObject

	ItemToMonitor       ReadValueId
	MonitoringMode      enumMonitoringMode
	RequestedParameters MonitoringParameters
}

type MonitoredItemCreateResult struct {
	ExtensionObject

	StatusCode              enumStatusCode
	MonitoredItemId         uint32
	RevisedSamplingInterval float64
	RevisedQueueSize        uint32
	FilterResult            ExtensionObject
}

type CreateMonitoredItemsRequest struct {
	ExtensionObject

	RequestHeader      RequestHeader
	SubscriptionId     uint32
	TimestampsToReturn enumTimestampsToReturn
	NoOfItemsToCreate  int32
	ItemsToCreate      []MonitoredItemCreateRequest `opcua:"lengthField=NoOfItemsToCreate"`
}

type CreateMonitoredItemsResponse struct {
	ExtensionObject

	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []MonitoredItemCreateResult `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type MonitoredItemModifyRequest struct {
	ExtensionObject

	MonitoredItemId     uint32
	RequestedParameters MonitoringParameters
}

type MonitoredItemModifyResult struct {
	ExtensionObject

	StatusCode              enumStatusCode
	RevisedSamplingInterval float64
	RevisedQueueSize        uint32
	FilterResult            ExtensionObject
}

type ModifyMonitoredItemsRequest struct {
	ExtensionObject

	RequestHeader      RequestHeader
	SubscriptionId     uint32
	TimestampsToReturn enumTimestampsToReturn
	NoOfItemsToModify  int32
	ItemsToModify      []MonitoredItemModifyRequest `opcua:"lengthField=NoOfItemsToModify"`
}

type ModifyMonitoredItemsResponse struct {
	ExtensionObject

	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []MonitoredItemModifyResult `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type SetMonitoringModeRequest struct {
	ExtensionObject

	RequestHeader        RequestHeader
	SubscriptionId       uint32
	MonitoringMode       enumMonitoringMode
	NoOfMonitoredItemIds int32
	MonitoredItemIds     []uint32 `opcua:"lengthField=NoOfMonitoredItemIds"`
}

type SetMonitoringModeResponse struct {
	ExtensionObject

	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []enumStatusCode `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type SetTriggeringRequest struct {
	ExtensionObject

	RequestHeader     RequestHeader
	SubscriptionId    uint32
	TriggeringItemId  uint32
	NoOfLinksToAdd    int32
	LinksToAdd        []uint32 `opcua:"lengthField=NoOfLinksToAdd"`
	NoOfLinksToRemove int32
	LinksToRemove     []uint32 `opcua:"lengthField=NoOfLinksToRemove"`
}

type SetTriggeringResponse struct {
	ExtensionObject

	ResponseHeader            ResponseHeader
	NoOfAddResults            int32
	AddResults                []enumStatusCode `opcua:"lengthField=NoOfAddResults"`
	NoOfAddDiagnosticInfos    int32
	AddDiagnosticInfos        []DiagnosticInfo `opcua:"lengthField=NoOfAddDiagnosticInfos"`
	NoOfRemoveResults         int32
	RemoveResults             []enumStatusCode `opcua:"lengthField=NoOfRemoveResults"`
	NoOfRemoveDiagnosticInfos int32
	RemoveDiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfRemoveDiagnosticInfos"`
}

type DeleteMonitoredItemsRequest struct {
	ExtensionObject

	RequestHeader        RequestHeader
	SubscriptionId       uint32
	NoOfMonitoredItemIds int32
	MonitoredItemIds     []uint32 `opcua:"lengthField=NoOfMonitoredItemIds"`
}

type DeleteMonitoredItemsResponse struct {
	ExtensionObject

	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []enumStatusCode `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type CreateSubscriptionRequest struct {
	ExtensionObject

	RequestHeader               RequestHeader
	RequestedPublishingInterval float64
	RequestedLifetimeCount      uint32
	RequestedMaxKeepAliveCount  uint32
	MaxNotificationsPerPublish  uint32
	PublishingEnabled           bool
	Priority                    uint8
}

type CreateSubscriptionResponse struct {
	ExtensionObject

	ResponseHeader            ResponseHeader
	SubscriptionId            uint32
	RevisedPublishingInterval float64
	RevisedLifetimeCount      uint32
	RevisedMaxKeepAliveCount  uint32
}

type ModifySubscriptionRequest struct {
	ExtensionObject

	RequestHeader               RequestHeader
	SubscriptionId              uint32
	RequestedPublishingInterval float64
	RequestedLifetimeCount      uint32
	RequestedMaxKeepAliveCount  uint32
	MaxNotificationsPerPublish  uint32
	Priority                    uint8
}

type ModifySubscriptionResponse struct {
	ExtensionObject

	ResponseHeader            ResponseHeader
	RevisedPublishingInterval float64
	RevisedLifetimeCount      uint32
	RevisedMaxKeepAliveCount  uint32
}

type SetPublishingModeRequest struct {
	ExtensionObject

	RequestHeader       RequestHeader
	PublishingEnabled   bool
	NoOfSubscriptionIds int32
	SubscriptionIds     []uint32 `opcua:"lengthField=NoOfSubscriptionIds"`
}

type SetPublishingModeResponse struct {
	ExtensionObject

	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []enumStatusCode `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type NotificationMessage struct {
	ExtensionObject

	SequenceNumber       uint32
	PublishTime          time.Time
	NoOfNotificationData int32
	NotificationData     []ExtensionObject `opcua:"lengthField=NoOfNotificationData"`
}

type NotificationData struct {
	ExtensionObject
}

type DataChangeNotification struct {
	NotificationData

	NoOfMonitoredItems  int32
	MonitoredItems      []MonitoredItemNotification `opcua:"lengthField=NoOfMonitoredItems"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type MonitoredItemNotification struct {
	ExtensionObject

	ClientHandle uint32
	Value        DataValue
}

type EventNotificationList struct {
	NotificationData

	NoOfEvents int32
	Events     []EventFieldList `opcua:"lengthField=NoOfEvents"`
}

type EventFieldList struct {
	ExtensionObject

	ClientHandle    uint32
	NoOfEventFields int32
	EventFields     []Variant `opcua:"lengthField=NoOfEventFields"`
}

type HistoryEventFieldList struct {
	ExtensionObject

	NoOfEventFields int32
	EventFields     []Variant `opcua:"lengthField=NoOfEventFields"`
}

type StatusChangeNotification struct {
	NotificationData

	Status         enumStatusCode
	DiagnosticInfo *DiagnosticInfo
}

type SubscriptionAcknowledgement struct {
	ExtensionObject

	SubscriptionId uint32
	SequenceNumber uint32
}

type PublishRequest struct {
	ExtensionObject

	RequestHeader                    RequestHeader
	NoOfSubscriptionAcknowledgements int32
	SubscriptionAcknowledgements     []SubscriptionAcknowledgement `opcua:"lengthField=NoOfSubscriptionAcknowledgements"`
}

type PublishResponse struct {
	ExtensionObject

	ResponseHeader               ResponseHeader
	SubscriptionId               uint32
	NoOfAvailableSequenceNumbers int32
	AvailableSequenceNumbers     []uint32 `opcua:"lengthField=NoOfAvailableSequenceNumbers"`
	MoreNotifications            bool
	NotificationMessage          NotificationMessage
	NoOfResults                  int32
	Results                      []enumStatusCode `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos          int32
	DiagnosticInfos              []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type RepublishRequest struct {
	ExtensionObject

	RequestHeader            RequestHeader
	SubscriptionId           uint32
	RetransmitSequenceNumber uint32
}

type RepublishResponse struct {
	ExtensionObject

	ResponseHeader      ResponseHeader
	NotificationMessage NotificationMessage
}

type TransferResult struct {
	ExtensionObject

	StatusCode                   enumStatusCode
	NoOfAvailableSequenceNumbers int32
	AvailableSequenceNumbers     []uint32 `opcua:"lengthField=NoOfAvailableSequenceNumbers"`
}

type TransferSubscriptionsRequest struct {
	ExtensionObject

	RequestHeader       RequestHeader
	NoOfSubscriptionIds int32
	SubscriptionIds     []uint32 `opcua:"lengthField=NoOfSubscriptionIds"`
	SendInitialValues   bool
}

type TransferSubscriptionsResponse struct {
	ExtensionObject

	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []TransferResult `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type DeleteSubscriptionsRequest struct {
	ExtensionObject

	RequestHeader       RequestHeader
	NoOfSubscriptionIds int32
	SubscriptionIds     []uint32 `opcua:"lengthField=NoOfSubscriptionIds"`
}

type DeleteSubscriptionsResponse struct {
	ExtensionObject

	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []enumStatusCode `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type BuildInfo struct {
	ExtensionObject

	ProductUri       String
	ManufacturerName String
	ProductName      String
	SoftwareVersion  String
	BuildNumber      String
	BuildDate        time.Time
}

type RedundantServerDataType struct {
	ExtensionObject

	ServerId     String
	ServiceLevel uint8
	ServerState  enumServerState
}

type EndpointUrlListDataType struct {
	ExtensionObject

	NoOfEndpointUrlList int32
	EndpointUrlList     []String `opcua:"lengthField=NoOfEndpointUrlList"`
}

type NetworkGroupDataType struct {
	ExtensionObject

	ServerUri        String
	NoOfNetworkPaths int32
	NetworkPaths     []EndpointUrlListDataType `opcua:"lengthField=NoOfNetworkPaths"`
}

type SamplingIntervalDiagnosticsDataType struct {
	ExtensionObject

	SamplingInterval           float64
	MonitoredItemCount         uint32
	MaxMonitoredItemCount      uint32
	DisabledMonitoredItemCount uint32
}

type ServerDiagnosticsSummaryDataType struct {
	ExtensionObject

	ServerViewCount               uint32
	CurrentSessionCount           uint32
	CumulatedSessionCount         uint32
	SecurityRejectedSessionCount  uint32
	RejectedSessionCount          uint32
	SessionTimeoutCount           uint32
	SessionAbortCount             uint32
	CurrentSubscriptionCount      uint32
	CumulatedSubscriptionCount    uint32
	PublishingIntervalCount       uint32
	SecurityRejectedRequestsCount uint32
	RejectedRequestsCount         uint32
}

type ServerStatusDataType struct {
	ExtensionObject

	StartTime           time.Time
	CurrentTime         time.Time
	State               enumServerState
	BuildInfo           BuildInfo
	SecondsTillShutdown uint32
	ShutdownReason      LocalizedText
}

type SessionDiagnosticsDataType struct {
	ExtensionObject

	SessionId                          NodeId
	SessionName                        String
	ClientDescription                  ApplicationDescription
	ServerUri                          String
	EndpointUrl                        String
	NoOfLocaleIds                      int32
	LocaleIds                          []String `opcua:"lengthField=NoOfLocaleIds"`
	ActualSessionTimeout               float64
	MaxResponseMessageSize             uint32
	ClientConnectionTime               time.Time
	ClientLastContactTime              time.Time
	CurrentSubscriptionsCount          uint32
	CurrentMonitoredItemsCount         uint32
	CurrentPublishRequestsInQueue      uint32
	TotalRequestCount                  ServiceCounterDataType
	UnauthorizedRequestCount           uint32
	ReadCount                          ServiceCounterDataType
	HistoryReadCount                   ServiceCounterDataType
	WriteCount                         ServiceCounterDataType
	HistoryUpdateCount                 ServiceCounterDataType
	CallCount                          ServiceCounterDataType
	CreateMonitoredItemsCount          ServiceCounterDataType
	ModifyMonitoredItemsCount          ServiceCounterDataType
	SetMonitoringModeCount             ServiceCounterDataType
	SetTriggeringCount                 ServiceCounterDataType
	DeleteMonitoredItemsCount          ServiceCounterDataType
	CreateSubscriptionCount            ServiceCounterDataType
	ModifySubscriptionCount            ServiceCounterDataType
	SetPublishingModeCount             ServiceCounterDataType
	PublishCount                       ServiceCounterDataType
	RepublishCount                     ServiceCounterDataType
	TransferSubscriptionsCount         ServiceCounterDataType
	DeleteSubscriptionsCount           ServiceCounterDataType
	AddNodesCount                      ServiceCounterDataType
	AddReferencesCount                 ServiceCounterDataType
	DeleteNodesCount                   ServiceCounterDataType
	DeleteReferencesCount              ServiceCounterDataType
	BrowseCount                        ServiceCounterDataType
	BrowseNextCount                    ServiceCounterDataType
	TranslateBrowsePathsToNodeIdsCount ServiceCounterDataType
	QueryFirstCount                    ServiceCounterDataType
	QueryNextCount                     ServiceCounterDataType
	RegisterNodesCount                 ServiceCounterDataType
	UnregisterNodesCount               ServiceCounterDataType
}

type SessionSecurityDiagnosticsDataType struct {
	ExtensionObject

	SessionId               NodeId
	ClientUserIdOfSession   String
	NoOfClientUserIdHistory int32
	ClientUserIdHistory     []String `opcua:"lengthField=NoOfClientUserIdHistory"`
	AuthenticationMechanism String
	Encoding                String
	TransportProtocol       String
	SecurityMode            enumMessageSecurityMode
	SecurityPolicyUri       String
	ClientCertificate       ByteString
}

type ServiceCounterDataType struct {
	ExtensionObject

	TotalCount uint32
	ErrorCount uint32
}

type StatusResult struct {
	ExtensionObject

	StatusCode     enumStatusCode
	DiagnosticInfo *DiagnosticInfo
}

type SubscriptionDiagnosticsDataType struct {
	ExtensionObject

	SessionId                    NodeId
	SubscriptionId               uint32
	Priority                     uint8
	PublishingInterval           float64
	MaxKeepAliveCount            uint32
	MaxLifetimeCount             uint32
	MaxNotificationsPerPublish   uint32
	PublishingEnabled            bool
	ModifyCount                  uint32
	EnableCount                  uint32
	DisableCount                 uint32
	RepublishRequestCount        uint32
	RepublishMessageRequestCount uint32
	RepublishMessageCount        uint32
	TransferRequestCount         uint32
	TransferredToAltClientCount  uint32
	TransferredToSameClientCount uint32
	PublishRequestCount          uint32
	DataChangeNotificationsCount uint32
	EventNotificationsCount      uint32
	NotificationsCount           uint32
	LatePublishRequestCount      uint32
	CurrentKeepAliveCount        uint32
	CurrentLifetimeCount         uint32
	UnacknowledgedMessageCount   uint32
	DiscardedMessageCount        uint32
	MonitoredItemCount           uint32
	DisabledMonitoredItemCount   uint32
	MonitoringQueueOverflowCount uint32
	NextSequenceNumber           uint32
	EventQueueOverFlowCount      uint32
}

type ModelChangeStructureDataType struct {
	ExtensionObject

	Affected     NodeId
	AffectedType NodeId
	Verb         uint8
}

type SemanticChangeStructureDataType struct {
	ExtensionObject

	Affected     NodeId
	AffectedType NodeId
}

type Range struct {
	ExtensionObject

	Low  float64
	High float64
}

type EUInformation struct {
	ExtensionObject

	NamespaceUri String
	UnitId       int32
	DisplayName  LocalizedText
	Description  LocalizedText
}

type ComplexNumberType struct {
	ExtensionObject

	Real      float32
	Imaginary float32
}

type DoubleComplexNumberType struct {
	ExtensionObject

	Real      float64
	Imaginary float64
}

type AxisInformation struct {
	ExtensionObject

	EngineeringUnits EUInformation
	EURange          Range
	Title            LocalizedText
	AxisScaleType    enumAxisScaleEnumeration
	NoOfAxisSteps    int32
	AxisSteps        []float64 `opcua:"lengthField=NoOfAxisSteps"`
}

type XVType struct {
	ExtensionObject

	X     float64
	Value float32
}

type ProgramDiagnosticDataType struct {
	ExtensionObject

	CreateSessionId               NodeId
	CreateClientName              String
	InvocationCreationTime        time.Time
	LastTransitionTime            time.Time
	LastMethodCall                String
	LastMethodSessionId           NodeId
	NoOfLastMethodInputArguments  int32
	LastMethodInputArguments      []Argument `opcua:"lengthField=NoOfLastMethodInputArguments"`
	NoOfLastMethodOutputArguments int32
	LastMethodOutputArguments     []Argument `opcua:"lengthField=NoOfLastMethodOutputArguments"`
	LastMethodCallTime            time.Time
	LastMethodReturnStatus        StatusResult
}

type Annotation struct {
	ExtensionObject

	Message        String
	UserName       String
	AnnotationTime time.Time
}
