// DO NOT EDIT. Generated by csv2code.

package uatype

// attrType is a private type used for enumeration values.
type attrType uint8

const (
	AttrTypeNodeId                  attrType = 1
	AttrTypeNodeClass               attrType = 2
	AttrTypeBrowseName              attrType = 3
	AttrTypeDisplayName             attrType = 4
	AttrTypeDescription             attrType = 5
	AttrTypeWriteMask               attrType = 6
	AttrTypeUserWriteMask           attrType = 7
	AttrTypeIsAbstract              attrType = 8
	AttrTypeSymmetric               attrType = 9
	AttrTypeInverseName             attrType = 10
	AttrTypeContainsNoLoops         attrType = 11
	AttrTypeEventNotifier           attrType = 12
	AttrTypeValue                   attrType = 13
	AttrTypeDataType                attrType = 14
	AttrTypeValueRank               attrType = 15
	AttrTypeArrayDimensions         attrType = 16
	AttrTypeAccessLevel             attrType = 17
	AttrTypeUserAccessLevel         attrType = 18
	AttrTypeMinimumSamplingInterval attrType = 19
	AttrTypeHistorizing             attrType = 20
	AttrTypeExecutable              attrType = 21
	AttrTypeUserExecutable          attrType = 22
)
