// Code generated by opcua-xml2code. DO NOT EDIT.

package uatype

import "time"

type NodeIdType byte

// BitLength returns the number of bits that should be used for encoding this value.
func (t NodeIdType) BitLength() int {
	return 6
}

// The possible encodings for a NodeId value.
const (
	NodeIdTypeTwoByte    NodeIdType = 0
	NodeIdTypeFourByte   NodeIdType = 1
	NodeIdTypeNumeric    NodeIdType = 2
	NodeIdTypeString     NodeIdType = 3
	NodeIdTypeGuid       NodeIdType = 4
	NodeIdTypeByteString NodeIdType = 5
)

type NamingRuleType uint32

const (
	NamingRuleTypeMandatory  NamingRuleType = 1
	NamingRuleTypeOptional   NamingRuleType = 2
	NamingRuleTypeConstraint NamingRuleType = 3
)

type OpenFileMode uint32

const (
	OpenFileModeRead          OpenFileMode = 1
	OpenFileModeWrite         OpenFileMode = 2
	OpenFileModeEraseExisting OpenFileMode = 4
	OpenFileModeAppend        OpenFileMode = 8
)

type TrustListMasks uint32

const (
	TrustListMasksNone                TrustListMasks = 0
	TrustListMasksTrustedCertificates TrustListMasks = 1
	TrustListMasksTrustedCrls         TrustListMasks = 2
	TrustListMasksIssuerCertificates  TrustListMasks = 4
	TrustListMasksIssuerCrls          TrustListMasks = 8
	TrustListMasksAll                 TrustListMasks = 15
)

type IdType uint32

// The type of identifier used in a node id.
const (
	IdTypeNumeric IdType = 0
	IdTypeString  IdType = 1
	IdTypeGuid    IdType = 2
	IdTypeOpaque  IdType = 3
)

type NodeClass uint32

// A mask specifying the class of the node.
const (
	NodeClassUnspecified   NodeClass = 0
	NodeClassObject        NodeClass = 1
	NodeClassVariable      NodeClass = 2
	NodeClassMethod        NodeClass = 4
	NodeClassObjectType    NodeClass = 8
	NodeClassVariableType  NodeClass = 16
	NodeClassReferenceType NodeClass = 32
	NodeClassDataType      NodeClass = 64
	NodeClassView          NodeClass = 128
)

type ApplicationType uint32

// The types of applications.
const (
	ApplicationTypeServer          ApplicationType = 0
	ApplicationTypeClient          ApplicationType = 1
	ApplicationTypeClientAndServer ApplicationType = 2
	ApplicationTypeDiscoveryServer ApplicationType = 3
)

type MessageSecurityMode uint32

// The type of security to use on a message.
const (
	MessageSecurityModeInvalid        MessageSecurityMode = 0
	MessageSecurityModeNone           MessageSecurityMode = 1
	MessageSecurityModeSign           MessageSecurityMode = 2
	MessageSecurityModeSignAndEncrypt MessageSecurityMode = 3
)

type UserTokenType uint32

// The possible user token types.
const (
	UserTokenTypeAnonymous   UserTokenType = 0
	UserTokenTypeUserName    UserTokenType = 1
	UserTokenTypeCertificate UserTokenType = 2
	UserTokenTypeIssuedToken UserTokenType = 3
)

type SecurityTokenRequestType uint32

// Indicates whether a token if being created or renewed.
const (
	SecurityTokenRequestTypeIssue SecurityTokenRequestType = 0
	SecurityTokenRequestTypeRenew SecurityTokenRequestType = 1
)

type NodeAttributesMask uint32

// The bits used to specify default attributes for a new node.
const (
	NodeAttributesMaskNone                    NodeAttributesMask = 0
	NodeAttributesMaskAccessLevel             NodeAttributesMask = 1
	NodeAttributesMaskArrayDimensions         NodeAttributesMask = 2
	NodeAttributesMaskBrowseName              NodeAttributesMask = 4
	NodeAttributesMaskContainsNoLoops         NodeAttributesMask = 8
	NodeAttributesMaskDataType                NodeAttributesMask = 16
	NodeAttributesMaskDescription             NodeAttributesMask = 32
	NodeAttributesMaskDisplayName             NodeAttributesMask = 64
	NodeAttributesMaskEventNotifier           NodeAttributesMask = 128
	NodeAttributesMaskExecutable              NodeAttributesMask = 256
	NodeAttributesMaskHistorizing             NodeAttributesMask = 512
	NodeAttributesMaskInverseName             NodeAttributesMask = 1024
	NodeAttributesMaskIsAbstract              NodeAttributesMask = 2048
	NodeAttributesMaskMinimumSamplingInterval NodeAttributesMask = 4096
	NodeAttributesMaskNodeClass               NodeAttributesMask = 8192
	NodeAttributesMaskNodeId                  NodeAttributesMask = 16384
	NodeAttributesMaskSymmetric               NodeAttributesMask = 32768
	NodeAttributesMaskUserAccessLevel         NodeAttributesMask = 65536
	NodeAttributesMaskUserExecutable          NodeAttributesMask = 131072
	NodeAttributesMaskUserWriteMask           NodeAttributesMask = 262144
	NodeAttributesMaskValueRank               NodeAttributesMask = 524288
	NodeAttributesMaskWriteMask               NodeAttributesMask = 1048576
	NodeAttributesMaskValue                   NodeAttributesMask = 2097152
	NodeAttributesMaskAll                     NodeAttributesMask = 4194303
	NodeAttributesMaskBaseNode                NodeAttributesMask = 1335396
	NodeAttributesMaskObject                  NodeAttributesMask = 1335524
	NodeAttributesMaskObjectTypeOrDataType    NodeAttributesMask = 1337444
	NodeAttributesMaskVariable                NodeAttributesMask = 4026999
	NodeAttributesMaskVariableType            NodeAttributesMask = 3958902
	NodeAttributesMaskMethod                  NodeAttributesMask = 1466724
	NodeAttributesMaskReferenceType           NodeAttributesMask = 1371236
	NodeAttributesMaskView                    NodeAttributesMask = 1335532
)

type AttributeWriteMask uint32

// Define bits used to indicate which attributes are writable.
const (
	AttributeWriteMaskNone                    AttributeWriteMask = 0
	AttributeWriteMaskAccessLevel             AttributeWriteMask = 1
	AttributeWriteMaskArrayDimensions         AttributeWriteMask = 2
	AttributeWriteMaskBrowseName              AttributeWriteMask = 4
	AttributeWriteMaskContainsNoLoops         AttributeWriteMask = 8
	AttributeWriteMaskDataType                AttributeWriteMask = 16
	AttributeWriteMaskDescription             AttributeWriteMask = 32
	AttributeWriteMaskDisplayName             AttributeWriteMask = 64
	AttributeWriteMaskEventNotifier           AttributeWriteMask = 128
	AttributeWriteMaskExecutable              AttributeWriteMask = 256
	AttributeWriteMaskHistorizing             AttributeWriteMask = 512
	AttributeWriteMaskInverseName             AttributeWriteMask = 1024
	AttributeWriteMaskIsAbstract              AttributeWriteMask = 2048
	AttributeWriteMaskMinimumSamplingInterval AttributeWriteMask = 4096
	AttributeWriteMaskNodeClass               AttributeWriteMask = 8192
	AttributeWriteMaskNodeId                  AttributeWriteMask = 16384
	AttributeWriteMaskSymmetric               AttributeWriteMask = 32768
	AttributeWriteMaskUserAccessLevel         AttributeWriteMask = 65536
	AttributeWriteMaskUserExecutable          AttributeWriteMask = 131072
	AttributeWriteMaskUserWriteMask           AttributeWriteMask = 262144
	AttributeWriteMaskValueRank               AttributeWriteMask = 524288
	AttributeWriteMaskWriteMask               AttributeWriteMask = 1048576
	AttributeWriteMaskValueForVariableType    AttributeWriteMask = 2097152
)

type BrowseDirection uint32

// The directions of the references to return.
const (
	BrowseDirectionForward BrowseDirection = 0
	BrowseDirectionInverse BrowseDirection = 1
	BrowseDirectionBoth    BrowseDirection = 2
	BrowseDirectionInvalid BrowseDirection = 3
)

type BrowseResultMask uint32

// A bit mask which specifies what should be returned in a browse response.
const (
	BrowseResultMaskNone              BrowseResultMask = 0
	BrowseResultMaskReferenceTypeId   BrowseResultMask = 1
	BrowseResultMaskIsForward         BrowseResultMask = 2
	BrowseResultMaskNodeClass         BrowseResultMask = 4
	BrowseResultMaskBrowseName        BrowseResultMask = 8
	BrowseResultMaskDisplayName       BrowseResultMask = 16
	BrowseResultMaskTypeDefinition    BrowseResultMask = 32
	BrowseResultMaskAll               BrowseResultMask = 63
	BrowseResultMaskReferenceTypeInfo BrowseResultMask = 3
	BrowseResultMaskTargetInfo        BrowseResultMask = 60
)

type FilterOperator uint32

const (
	FilterOperatorEquals             FilterOperator = 0
	FilterOperatorIsNull             FilterOperator = 1
	FilterOperatorGreaterThan        FilterOperator = 2
	FilterOperatorLessThan           FilterOperator = 3
	FilterOperatorGreaterThanOrEqual FilterOperator = 4
	FilterOperatorLessThanOrEqual    FilterOperator = 5
	FilterOperatorLike               FilterOperator = 6
	FilterOperatorNot                FilterOperator = 7
	FilterOperatorBetween            FilterOperator = 8
	FilterOperatorInList             FilterOperator = 9
	FilterOperatorAnd                FilterOperator = 10
	FilterOperatorOr                 FilterOperator = 11
	FilterOperatorCast               FilterOperator = 12
	FilterOperatorInView             FilterOperator = 13
	FilterOperatorOfType             FilterOperator = 14
	FilterOperatorRelatedTo          FilterOperator = 15
	FilterOperatorBitwiseAnd         FilterOperator = 16
	FilterOperatorBitwiseOr          FilterOperator = 17
)

type TimestampsToReturn uint32

const (
	TimestampsToReturnSource  TimestampsToReturn = 0
	TimestampsToReturnServer  TimestampsToReturn = 1
	TimestampsToReturnBoth    TimestampsToReturn = 2
	TimestampsToReturnNeither TimestampsToReturn = 3
	TimestampsToReturnInvalid TimestampsToReturn = 4
)

type HistoryUpdateType uint32

const (
	HistoryUpdateTypeInsert  HistoryUpdateType = 1
	HistoryUpdateTypeReplace HistoryUpdateType = 2
	HistoryUpdateTypeUpdate  HistoryUpdateType = 3
	HistoryUpdateTypeDelete  HistoryUpdateType = 4
)

type PerformUpdateType uint32

const (
	PerformUpdateTypeInsert  PerformUpdateType = 1
	PerformUpdateTypeReplace PerformUpdateType = 2
	PerformUpdateTypeUpdate  PerformUpdateType = 3
	PerformUpdateTypeRemove  PerformUpdateType = 4
)

type MonitoringMode uint32

const (
	MonitoringModeDisabled  MonitoringMode = 0
	MonitoringModeSampling  MonitoringMode = 1
	MonitoringModeReporting MonitoringMode = 2
)

type DataChangeTrigger uint32

const (
	DataChangeTriggerStatus               DataChangeTrigger = 0
	DataChangeTriggerStatusValue          DataChangeTrigger = 1
	DataChangeTriggerStatusValueTimestamp DataChangeTrigger = 2
)

type DeadbandType uint32

const (
	DeadbandTypeNone     DeadbandType = 0
	DeadbandTypeAbsolute DeadbandType = 1
	DeadbandTypePercent  DeadbandType = 2
)

type RedundancySupport uint32

const (
	RedundancySupportNone           RedundancySupport = 0
	RedundancySupportCold           RedundancySupport = 1
	RedundancySupportWarm           RedundancySupport = 2
	RedundancySupportHot            RedundancySupport = 3
	RedundancySupportTransparent    RedundancySupport = 4
	RedundancySupportHotAndMirrored RedundancySupport = 5
)

type ServerState uint32

const (
	ServerStateRunning            ServerState = 0
	ServerStateFailed             ServerState = 1
	ServerStateNoConfiguration    ServerState = 2
	ServerStateSuspended          ServerState = 3
	ServerStateShutdown           ServerState = 4
	ServerStateTest               ServerState = 5
	ServerStateCommunicationFault ServerState = 6
	ServerStateUnknown            ServerState = 7
)

type ModelChangeStructureVerbMask uint32

const (
	ModelChangeStructureVerbMaskNodeAdded        ModelChangeStructureVerbMask = 1
	ModelChangeStructureVerbMaskNodeDeleted      ModelChangeStructureVerbMask = 2
	ModelChangeStructureVerbMaskReferenceAdded   ModelChangeStructureVerbMask = 4
	ModelChangeStructureVerbMaskReferenceDeleted ModelChangeStructureVerbMask = 8
	ModelChangeStructureVerbMaskDataTypeChanged  ModelChangeStructureVerbMask = 16
)

type AxisScaleEnumeration uint32

const (
	AxisScaleEnumerationLinear AxisScaleEnumeration = 0
	AxisScaleEnumerationLog    AxisScaleEnumeration = 1
	AxisScaleEnumerationLn     AxisScaleEnumeration = 2
)

type ExceptionDeviationFormat uint32

const (
	ExceptionDeviationFormatAbsoluteValue    ExceptionDeviationFormat = 0
	ExceptionDeviationFormatPercentOfValue   ExceptionDeviationFormat = 1
	ExceptionDeviationFormatPercentOfRange   ExceptionDeviationFormat = 2
	ExceptionDeviationFormatPercentOfEURange ExceptionDeviationFormat = 3
	ExceptionDeviationFormatUnknown          ExceptionDeviationFormat = 4
)

// XmlElement is an XML element encoded as a UTF-8 string.
type XmlElement struct {
	Length int32
	Value  []rune `opcua:"lengthField=Length"`
}

type TwoByteNodeId struct {
	Identifier uint8
}

type FourByteNodeId struct {
	NamespaceIndex uint8
	Identifier     uint16
}

type NumericNodeId struct {
	NamespaceIndex uint16
	Identifier     uint32
}

type StringNodeId struct {
	NamespaceIndex uint16
	Identifier     string
}

type GuidNodeId struct {
	NamespaceIndex uint16
	Identifier     Guid
}

type ByteStringNodeId struct {
	NamespaceIndex uint16
	Identifier     ByteString
}

// NodeId is an identifier for a node in a UA server address space.
type NodeId struct {
	NodeIdType NodeIdType
	Reserved1  byte             `opcua:"bits=2"`
	TwoByte    TwoByteNodeId    `opcua:"switchField=NodeIdType,switchValue=0"`
	FourByte   FourByteNodeId   `opcua:"switchField=NodeIdType,switchValue=1"`
	Numeric    NumericNodeId    `opcua:"switchField=NodeIdType,switchValue=2"`
	String     StringNodeId     `opcua:"switchField=NodeIdType,switchValue=3"`
	Guid       GuidNodeId       `opcua:"switchField=NodeIdType,switchValue=4"`
	ByteString ByteStringNodeId `opcua:"switchField=NodeIdType,switchValue=5"`
}

// ExpandedNodeId is an identifier for a node in a UA server address space qualified with a complete namespace string.
type ExpandedNodeId struct {
	NodeIdType            NodeIdType
	ServerIndexSpecified  Bit
	NamespaceURISpecified Bit
	TwoByte               TwoByteNodeId    `opcua:"switchField=NodeIdType,switchValue=0"`
	FourByte              FourByteNodeId   `opcua:"switchField=NodeIdType,switchValue=1"`
	Numeric               NumericNodeId    `opcua:"switchField=NodeIdType,switchValue=2"`
	String                StringNodeId     `opcua:"switchField=NodeIdType,switchValue=3"`
	Guid                  GuidNodeId       `opcua:"switchField=NodeIdType,switchValue=4"`
	ByteString            ByteStringNodeId `opcua:"switchField=NodeIdType,switchValue=5"`
	NamespaceURI          string           `opcua:"switchField=NamespaceURISpecified"`
	ServerIndex           uint32           `opcua:"switchField=ServerIndexSpecified"`
}

// DiagnosticInfo is a recursive structure containing diagnostic information associated with a status code.
type DiagnosticInfo struct {
	SymbolicIdSpecified          Bit
	NamespaceURISpecified        Bit
	LocaleSpecified              Bit
	LocalizedTextSpecified       Bit
	AdditionalInfoSpecified      Bit
	InnerStatusCodeSpecified     Bit
	InnerDiagnosticInfoSpecified Bit
	Reserved1                    Bit
	SymbolicId                   int32           `opcua:"switchField=SymbolicIdSpecified"`
	NamespaceURI                 int32           `opcua:"switchField=NamespaceURISpecified"`
	Locale                       int32           `opcua:"switchField=LocaleSpecified"`
	LocalizedText                int32           `opcua:"switchField=LocalizedTextSpecified"`
	AdditionalInfo               string          `opcua:"switchField=AdditionalInfoSpecified"`
	InnerStatusCode              StatusCode      `opcua:"switchField=InnerStatusCodeSpecified"`
	InnerDiagnosticInfo          *DiagnosticInfo `opcua:"switchField=InnerDiagnosticInfoSpecified"`
}

// QualifiedName is a string qualified with a namespace index.
type QualifiedName struct {
	NamespaceIndex uint16
	Name           string
}

// LocalizedText is a string qualified with a namespace index.
type LocalizedText struct {
	LocaleSpecified Bit
	TextSpecified   Bit
	Reserved1       byte   `opcua:"bits=6"`
	Locale          string `opcua:"switchField=LocaleSpecified"`
	Text            string `opcua:"switchField=TextSpecified"`
}

// DataValue is a value with an associated timestamp, and quality.
type DataValue struct {
	ValueSpecified             Bit
	StatusCodeSpecified        Bit
	SourceTimestampSpecified   Bit
	SourcePicosecondsSpecified Bit
	ServerTimestampSpecified   Bit
	ServerPicosecondsSpecified Bit
	Reserved1                  byte       `opcua:"bits=2"`
	Value                      Variant    `opcua:"switchField=ValueSpecified"`
	StatusCode                 StatusCode `opcua:"switchField=StatusCodeSpecified"`
	SourceTimestamp            time.Time  `opcua:"switchField=SourceTimestampSpecified"`
	SourcePicoseconds          uint16     `opcua:"switchField=SourcePicosecondsSpecified"`
	ServerTimestamp            time.Time  `opcua:"switchField=ServerTimestampSpecified"`
	ServerPicoseconds          uint16     `opcua:"switchField=ServerPicosecondsSpecified"`
}

// ExtensionObject is a serialized object prefixed with its data type identifier.
type ExtensionObject struct {
	TypeId     ExpandedNodeId
	Encoding   uint8
	BodyLength int32   `opcua:"switchField=Encoding,switchValue=0,switchOperand=NotEqual"`
	Body       []uint8 `opcua:"lengthField=BodyLength,switchField=Encoding,switchValue=0,switchOperand=NotEqual"`
}

// Variant is a union of several types.
type Variant struct {
	VariantType              byte `opcua:"bits=6"`
	ArrayDimensionsSpecified Bit
	ArrayLengthSpecified     Bit
	ArrayLength              int32             `opcua:"switchField=ArrayLengthSpecified"`
	Boolean                  []bool            `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=1"`
	SByte                    []int8            `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=2"`
	Byte                     []uint8           `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=3"`
	Int16                    []int16           `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=4"`
	UInt16                   []uint16          `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=5"`
	Int32                    []int32           `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=6"`
	UInt32                   []uint32          `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=7"`
	Int64                    []int64           `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=8"`
	UInt64                   []uint64          `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=9"`
	Float                    []float32         `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=10"`
	Double                   []float64         `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=11"`
	String                   []string          `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=12"`
	DateTime                 []time.Time       `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=13"`
	Guid                     []Guid            `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=14"`
	ByteString               []ByteString      `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=15"`
	XmlElement               []XmlElement      `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=16"`
	NodeId                   []NodeId          `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=17"`
	ExpandedNodeId           []ExpandedNodeId  `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=18"`
	StatusCode               []StatusCode      `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=19"`
	QualifiedName            []QualifiedName   `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=20"`
	LocalizedText            []LocalizedText   `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=21"`
	ExtensionObject          []ExtensionObject `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=22"`
	DataValue                []DataValue       `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=23"`
	Variant                  []Variant         `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=24"`
	DiagnosticInfo           []DiagnosticInfo  `opcua:"lengthField=ArrayLength,switchField=VariantType,switchValue=25"`
	NoOfArrayDimensions      int32             `opcua:"switchField=ArrayDimensionsSpecified"`
	ArrayDimensions          []int32           `opcua:"lengthField=NoOfArrayDimensions,switchField=ArrayDimensionsSpecified"`
}

type TrustListDataType struct {
	SpecifiedLists          uint32
	NoOfTrustedCertificates int32
	TrustedCertificates     []ByteString `opcua:"lengthField=NoOfTrustedCertificates"`
	NoOfTrustedCrls         int32
	TrustedCrls             []ByteString `opcua:"lengthField=NoOfTrustedCrls"`
	NoOfIssuerCertificates  int32
	IssuerCertificates      []ByteString `opcua:"lengthField=NoOfIssuerCertificates"`
	NoOfIssuerCrls          int32
	IssuerCrls              []ByteString `opcua:"lengthField=NoOfIssuerCrls"`
}

// Node specifies the attributes which belong to all nodes.
type Node struct {
	NodeId         NodeId
	NodeClass      NodeClass
	BrowseName     QualifiedName
	DisplayName    LocalizedText
	Description    LocalizedText
	WriteMask      uint32
	UserWriteMask  uint32
	NoOfReferences int32
	References     []ReferenceNode `opcua:"lengthField=NoOfReferences"`
}

type InstanceNode struct {
	Node

	NodeId         NodeId
	NodeClass      NodeClass
	BrowseName     QualifiedName
	DisplayName    LocalizedText
	Description    LocalizedText
	WriteMask      uint32
	UserWriteMask  uint32
	NoOfReferences int32
	References     []ReferenceNode `opcua:"lengthField=NoOfReferences"`
}

type TypeNode struct {
	Node

	NodeId         NodeId
	NodeClass      NodeClass
	BrowseName     QualifiedName
	DisplayName    LocalizedText
	Description    LocalizedText
	WriteMask      uint32
	UserWriteMask  uint32
	NoOfReferences int32
	References     []ReferenceNode `opcua:"lengthField=NoOfReferences"`
}

// ObjectNode specifies the attributes which belong to object nodes.
type ObjectNode struct {
	InstanceNode

	NodeId         NodeId
	NodeClass      NodeClass
	BrowseName     QualifiedName
	DisplayName    LocalizedText
	Description    LocalizedText
	WriteMask      uint32
	UserWriteMask  uint32
	NoOfReferences int32
	References     []ReferenceNode `opcua:"lengthField=NoOfReferences"`
	EventNotifier  uint8
}

// ObjectTypeNode specifies the attributes which belong to object type nodes.
type ObjectTypeNode struct {
	TypeNode

	NodeId         NodeId
	NodeClass      NodeClass
	BrowseName     QualifiedName
	DisplayName    LocalizedText
	Description    LocalizedText
	WriteMask      uint32
	UserWriteMask  uint32
	NoOfReferences int32
	References     []ReferenceNode `opcua:"lengthField=NoOfReferences"`
	IsAbstract     bool
}

// VariableNode specifies the attributes which belong to variable nodes.
type VariableNode struct {
	InstanceNode

	NodeId                  NodeId
	NodeClass               NodeClass
	BrowseName              QualifiedName
	DisplayName             LocalizedText
	Description             LocalizedText
	WriteMask               uint32
	UserWriteMask           uint32
	NoOfReferences          int32
	References              []ReferenceNode `opcua:"lengthField=NoOfReferences"`
	Value                   Variant
	DataType                NodeId
	ValueRank               int32
	NoOfArrayDimensions     int32
	ArrayDimensions         []uint32 `opcua:"lengthField=NoOfArrayDimensions"`
	AccessLevel             uint8
	UserAccessLevel         uint8
	MinimumSamplingInterval float64
	Historizing             bool
}

// VariableTypeNode specifies the attributes which belong to variable type nodes.
type VariableTypeNode struct {
	TypeNode

	NodeId              NodeId
	NodeClass           NodeClass
	BrowseName          QualifiedName
	DisplayName         LocalizedText
	Description         LocalizedText
	WriteMask           uint32
	UserWriteMask       uint32
	NoOfReferences      int32
	References          []ReferenceNode `opcua:"lengthField=NoOfReferences"`
	Value               Variant
	DataType            NodeId
	ValueRank           int32
	NoOfArrayDimensions int32
	ArrayDimensions     []uint32 `opcua:"lengthField=NoOfArrayDimensions"`
	IsAbstract          bool
}

// ReferenceTypeNode specifies the attributes which belong to reference type nodes.
type ReferenceTypeNode struct {
	TypeNode

	NodeId         NodeId
	NodeClass      NodeClass
	BrowseName     QualifiedName
	DisplayName    LocalizedText
	Description    LocalizedText
	WriteMask      uint32
	UserWriteMask  uint32
	NoOfReferences int32
	References     []ReferenceNode `opcua:"lengthField=NoOfReferences"`
	IsAbstract     bool
	Symmetric      bool
	InverseName    LocalizedText
}

// MethodNode specifies the attributes which belong to method nodes.
type MethodNode struct {
	InstanceNode

	NodeId         NodeId
	NodeClass      NodeClass
	BrowseName     QualifiedName
	DisplayName    LocalizedText
	Description    LocalizedText
	WriteMask      uint32
	UserWriteMask  uint32
	NoOfReferences int32
	References     []ReferenceNode `opcua:"lengthField=NoOfReferences"`
	Executable     bool
	UserExecutable bool
}

type ViewNode struct {
	InstanceNode

	NodeId          NodeId
	NodeClass       NodeClass
	BrowseName      QualifiedName
	DisplayName     LocalizedText
	Description     LocalizedText
	WriteMask       uint32
	UserWriteMask   uint32
	NoOfReferences  int32
	References      []ReferenceNode `opcua:"lengthField=NoOfReferences"`
	ContainsNoLoops bool
	EventNotifier   uint8
}

type DataTypeNode struct {
	TypeNode

	NodeId         NodeId
	NodeClass      NodeClass
	BrowseName     QualifiedName
	DisplayName    LocalizedText
	Description    LocalizedText
	WriteMask      uint32
	UserWriteMask  uint32
	NoOfReferences int32
	References     []ReferenceNode `opcua:"lengthField=NoOfReferences"`
	IsAbstract     bool
}

// ReferenceNode specifies a reference which belongs to a node.
type ReferenceNode struct {
	ReferenceTypeId NodeId
	IsInverse       bool
	TargetId        ExpandedNodeId
}

// Argument is an argument for a method.
type Argument struct {
	Name                string
	DataType            NodeId
	ValueRank           int32
	NoOfArrayDimensions int32
	ArrayDimensions     []uint32 `opcua:"lengthField=NoOfArrayDimensions"`
	Description         LocalizedText
}

// EnumValueType is a mapping between a value of an enumerated type and a name and description.
type EnumValueType struct {
	Value       int64
	DisplayName LocalizedText
	Description LocalizedText
}

// OptionSet this abstract Structured DataType is the base DataType for all DataTypes representing a bit mask.
type OptionSet struct {
	Value     ByteString
	ValidBits ByteString
}

// Union this abstract DataType is the base DataType for all union DataTypes.
type Union struct {
}

type TimeZoneDataType struct {
	Offset                 int16
	DaylightSavingInOffset bool
}

// ApplicationDescription describes an application and how to find it.
type ApplicationDescription struct {
	ApplicationUri      string
	ProductUri          string
	ApplicationName     LocalizedText
	ApplicationType     ApplicationType
	GatewayServerUri    string
	DiscoveryProfileUri string
	NoOfDiscoveryUrls   int32
	DiscoveryUrls       []string `opcua:"lengthField=NoOfDiscoveryUrls"`
}

// RequestHeader the header passed with every server request.
type RequestHeader struct {
	AuthenticationToken NodeId
	Timestamp           time.Time
	RequestHandle       uint32
	ReturnDiagnostics   uint32
	AuditEntryId        string
	TimeoutHint         uint32
	AdditionalHeader    ExtensionObject
}

// ResponseHeader the header passed with every server response.
type ResponseHeader struct {
	Timestamp          time.Time
	RequestHandle      uint32
	ServiceResult      StatusCode
	ServiceDiagnostics *DiagnosticInfo
	NoOfStringTable    int32
	StringTable        []string `opcua:"lengthField=NoOfStringTable"`
	AdditionalHeader   ExtensionObject
}

// ServiceFault the response returned by all services when there is a service level error.
type ServiceFault struct {
	ResponseHeader ResponseHeader
}

// FindServersRequest finds the servers known to the discovery server.
type FindServersRequest struct {
	RequestHeader  RequestHeader
	EndpointUrl    string
	NoOfLocaleIds  int32
	LocaleIds      []string `opcua:"lengthField=NoOfLocaleIds"`
	NoOfServerUris int32
	ServerUris     []string `opcua:"lengthField=NoOfServerUris"`
}

// FindServersResponse finds the servers known to the discovery server.
type FindServersResponse struct {
	ResponseHeader ResponseHeader
	NoOfServers    int32
	Servers        []ApplicationDescription `opcua:"lengthField=NoOfServers"`
}

type ServerOnNetwork struct {
	RecordId               uint32
	ServerName             string
	DiscoveryUrl           string
	NoOfServerCapabilities int32
	ServerCapabilities     []string `opcua:"lengthField=NoOfServerCapabilities"`
}

type FindServersOnNetworkRequest struct {
	RequestHeader              RequestHeader
	StartingRecordId           uint32
	MaxRecordsToReturn         uint32
	NoOfServerCapabilityFilter int32
	ServerCapabilityFilter     []string `opcua:"lengthField=NoOfServerCapabilityFilter"`
}

type FindServersOnNetworkResponse struct {
	ResponseHeader       ResponseHeader
	LastCounterResetTime time.Time
	NoOfServers          int32
	Servers              []ServerOnNetwork `opcua:"lengthField=NoOfServers"`
}

// UserTokenPolicy describes a user token that can be used with a server.
type UserTokenPolicy struct {
	PolicyId          string
	TokenType         UserTokenType
	IssuedTokenType   string
	IssuerEndpointUrl string
	SecurityPolicyUri string
}

// EndpointDescription the description of a endpoint that can be used to access a server.
type EndpointDescription struct {
	EndpointUrl            string
	Server                 ApplicationDescription
	ServerCertificate      ByteString
	SecurityMode           MessageSecurityMode
	SecurityPolicyUri      string
	NoOfUserIdentityTokens int32
	UserIdentityTokens     []UserTokenPolicy `opcua:"lengthField=NoOfUserIdentityTokens"`
	TransportProfileUri    string
	SecurityLevel          uint8
}

// GetEndpointsRequest gets the endpoints used by the server.
type GetEndpointsRequest struct {
	RequestHeader   RequestHeader
	EndpointUrl     string
	NoOfLocaleIds   int32
	LocaleIds       []string `opcua:"lengthField=NoOfLocaleIds"`
	NoOfProfileUris int32
	ProfileUris     []string `opcua:"lengthField=NoOfProfileUris"`
}

// GetEndpointsResponse gets the endpoints used by the server.
type GetEndpointsResponse struct {
	ResponseHeader ResponseHeader
	NoOfEndpoints  int32
	Endpoints      []EndpointDescription `opcua:"lengthField=NoOfEndpoints"`
}

// RegisteredServer the information required to register a server with a discovery server.
type RegisteredServer struct {
	ServerUri         string
	ProductUri        string
	NoOfServerNames   int32
	ServerNames       []LocalizedText `opcua:"lengthField=NoOfServerNames"`
	ServerType        ApplicationType
	GatewayServerUri  string
	NoOfDiscoveryUrls int32
	DiscoveryUrls     []string `opcua:"lengthField=NoOfDiscoveryUrls"`
	SemaphoreFilePath string
	IsOnline          bool
}

// RegisterServerRequest registers a server with the discovery server.
type RegisterServerRequest struct {
	RequestHeader RequestHeader
	Server        RegisteredServer
}

// RegisterServerResponse registers a server with the discovery server.
type RegisterServerResponse struct {
	ResponseHeader ResponseHeader
}

// DiscoveryConfiguration is a base type for discovery configuration information.
type DiscoveryConfiguration struct {
}

// MdnsDiscoveryConfiguration the discovery information needed for mDNS registration.
type MdnsDiscoveryConfiguration struct {
	DiscoveryConfiguration

	MdnsServerName         string
	NoOfServerCapabilities int32
	ServerCapabilities     []string `opcua:"lengthField=NoOfServerCapabilities"`
}

type RegisterServer2Request struct {
	RequestHeader              RequestHeader
	Server                     RegisteredServer
	NoOfDiscoveryConfiguration int32
	DiscoveryConfiguration     []ExtensionObject `opcua:"lengthField=NoOfDiscoveryConfiguration"`
}

type RegisterServer2Response struct {
	ResponseHeader           ResponseHeader
	NoOfConfigurationResults int32
	ConfigurationResults     []StatusCode `opcua:"lengthField=NoOfConfigurationResults"`
	NoOfDiagnosticInfos      int32
	DiagnosticInfos          []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

// ChannelSecurityToken the token that identifies a set of keys for an active secure channel.
type ChannelSecurityToken struct {
	ChannelId       uint32
	TokenId         uint32
	CreatedAt       time.Time
	RevisedLifetime uint32
}

// OpenSecureChannelRequest creates a secure channel with a server.
type OpenSecureChannelRequest struct {
	RequestHeader         RequestHeader
	ClientProtocolVersion uint32
	RequestType           SecurityTokenRequestType
	SecurityMode          MessageSecurityMode
	ClientNonce           ByteString
	RequestedLifetime     uint32
}

// OpenSecureChannelResponse creates a secure channel with a server.
type OpenSecureChannelResponse struct {
	ResponseHeader        ResponseHeader
	ServerProtocolVersion uint32
	SecurityToken         ChannelSecurityToken
	ServerNonce           ByteString
}

// CloseSecureChannelRequest closes a secure channel.
type CloseSecureChannelRequest struct {
	RequestHeader RequestHeader
}

// CloseSecureChannelResponse closes a secure channel.
type CloseSecureChannelResponse struct {
	ResponseHeader ResponseHeader
}

// SignedSoftwareCertificate is a software certificate with a digital signature.
type SignedSoftwareCertificate struct {
	CertificateData ByteString
	Signature       ByteString
}

// SignatureData is a digital signature.
type SignatureData struct {
	Algorithm string
	Signature ByteString
}

// CreateSessionRequest creates a new session with the server.
type CreateSessionRequest struct {
	RequestHeader           RequestHeader
	ClientDescription       ApplicationDescription
	ServerUri               string
	EndpointUrl             string
	SessionName             string
	ClientNonce             ByteString
	ClientCertificate       ByteString
	RequestedSessionTimeout float64
	MaxResponseMessageSize  uint32
}

// CreateSessionResponse creates a new session with the server.
type CreateSessionResponse struct {
	ResponseHeader                 ResponseHeader
	SessionId                      NodeId
	AuthenticationToken            NodeId
	RevisedSessionTimeout          float64
	ServerNonce                    ByteString
	ServerCertificate              ByteString
	NoOfServerEndpoints            int32
	ServerEndpoints                []EndpointDescription `opcua:"lengthField=NoOfServerEndpoints"`
	NoOfServerSoftwareCertificates int32
	ServerSoftwareCertificates     []SignedSoftwareCertificate `opcua:"lengthField=NoOfServerSoftwareCertificates"`
	ServerSignature                SignatureData
	MaxRequestMessageSize          uint32
}

// UserIdentityToken is a base type for a user identity token.
type UserIdentityToken struct {
	ExtensionObject

	PolicyId string
}

// AnonymousIdentityToken is a token representing an anonymous user.
type AnonymousIdentityToken struct {
	UserIdentityToken

	PolicyId string
}

// UserNameIdentityToken is a token representing a user identified by a user name and password.
type UserNameIdentityToken struct {
	UserIdentityToken

	PolicyId            string
	UserName            string
	Password            ByteString
	EncryptionAlgorithm string
}

// X509IdentityToken is a token representing a user identified by an X509 certificate.
type X509IdentityToken struct {
	UserIdentityToken

	PolicyId        string
	CertificateData ByteString
}

// IssuedIdentityToken is a token representing a user identified by a WS-Security XML token.
type IssuedIdentityToken struct {
	UserIdentityToken

	PolicyId            string
	TokenData           ByteString
	EncryptionAlgorithm string
}

// ActivateSessionRequest activates a session with the server.
type ActivateSessionRequest struct {
	RequestHeader                  RequestHeader
	ClientSignature                SignatureData
	NoOfClientSoftwareCertificates int32
	ClientSoftwareCertificates     []SignedSoftwareCertificate `opcua:"lengthField=NoOfClientSoftwareCertificates"`
	NoOfLocaleIds                  int32
	LocaleIds                      []string `opcua:"lengthField=NoOfLocaleIds"`
	UserIdentityToken              ExtensionObject
	UserTokenSignature             SignatureData
}

// ActivateSessionResponse activates a session with the server.
type ActivateSessionResponse struct {
	ResponseHeader      ResponseHeader
	ServerNonce         ByteString
	NoOfResults         int32
	Results             []StatusCode `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

// CloseSessionRequest closes a session with the server.
type CloseSessionRequest struct {
	RequestHeader       RequestHeader
	DeleteSubscriptions bool
}

// CloseSessionResponse closes a session with the server.
type CloseSessionResponse struct {
	ResponseHeader ResponseHeader
}

// CancelRequest cancels an outstanding request.
type CancelRequest struct {
	RequestHeader RequestHeader
	RequestHandle uint32
}

// CancelResponse cancels an outstanding request.
type CancelResponse struct {
	ResponseHeader ResponseHeader
	CancelCount    uint32
}

// NodeAttributes the base attributes for all nodes.
type NodeAttributes struct {
	ExtensionObject

	SpecifiedAttributes uint32
	DisplayName         LocalizedText
	Description         LocalizedText
	WriteMask           uint32
	UserWriteMask       uint32
}

// ObjectAttributes the attributes for an object node.
type ObjectAttributes struct {
	NodeAttributes

	SpecifiedAttributes uint32
	DisplayName         LocalizedText
	Description         LocalizedText
	WriteMask           uint32
	UserWriteMask       uint32
	EventNotifier       uint8
}

// VariableAttributes the attributes for a variable node.
type VariableAttributes struct {
	NodeAttributes

	SpecifiedAttributes     uint32
	DisplayName             LocalizedText
	Description             LocalizedText
	WriteMask               uint32
	UserWriteMask           uint32
	Value                   Variant
	DataType                NodeId
	ValueRank               int32
	NoOfArrayDimensions     int32
	ArrayDimensions         []uint32 `opcua:"lengthField=NoOfArrayDimensions"`
	AccessLevel             uint8
	UserAccessLevel         uint8
	MinimumSamplingInterval float64
	Historizing             bool
}

// MethodAttributes the attributes for a method node.
type MethodAttributes struct {
	NodeAttributes

	SpecifiedAttributes uint32
	DisplayName         LocalizedText
	Description         LocalizedText
	WriteMask           uint32
	UserWriteMask       uint32
	Executable          bool
	UserExecutable      bool
}

// ObjectTypeAttributes the attributes for an object type node.
type ObjectTypeAttributes struct {
	NodeAttributes

	SpecifiedAttributes uint32
	DisplayName         LocalizedText
	Description         LocalizedText
	WriteMask           uint32
	UserWriteMask       uint32
	IsAbstract          bool
}

// VariableTypeAttributes the attributes for a variable type node.
type VariableTypeAttributes struct {
	NodeAttributes

	SpecifiedAttributes uint32
	DisplayName         LocalizedText
	Description         LocalizedText
	WriteMask           uint32
	UserWriteMask       uint32
	Value               Variant
	DataType            NodeId
	ValueRank           int32
	NoOfArrayDimensions int32
	ArrayDimensions     []uint32 `opcua:"lengthField=NoOfArrayDimensions"`
	IsAbstract          bool
}

// ReferenceTypeAttributes the attributes for a reference type node.
type ReferenceTypeAttributes struct {
	NodeAttributes

	SpecifiedAttributes uint32
	DisplayName         LocalizedText
	Description         LocalizedText
	WriteMask           uint32
	UserWriteMask       uint32
	IsAbstract          bool
	Symmetric           bool
	InverseName         LocalizedText
}

// DataTypeAttributes the attributes for a data type node.
type DataTypeAttributes struct {
	NodeAttributes

	SpecifiedAttributes uint32
	DisplayName         LocalizedText
	Description         LocalizedText
	WriteMask           uint32
	UserWriteMask       uint32
	IsAbstract          bool
}

// ViewAttributes the attributes for a view node.
type ViewAttributes struct {
	NodeAttributes

	SpecifiedAttributes uint32
	DisplayName         LocalizedText
	Description         LocalizedText
	WriteMask           uint32
	UserWriteMask       uint32
	ContainsNoLoops     bool
	EventNotifier       uint8
}

// AddNodesItem is a request to add a node to the server address space.
type AddNodesItem struct {
	ParentNodeId       ExpandedNodeId
	ReferenceTypeId    NodeId
	RequestedNewNodeId ExpandedNodeId
	BrowseName         QualifiedName
	NodeClass          NodeClass
	NodeAttributes     ExtensionObject
	TypeDefinition     ExpandedNodeId
}

// AddNodesResult is a result of an add node operation.
type AddNodesResult struct {
	StatusCode  StatusCode
	AddedNodeId NodeId
}

// AddNodesRequest adds one or more nodes to the server address space.
type AddNodesRequest struct {
	RequestHeader  RequestHeader
	NoOfNodesToAdd int32
	NodesToAdd     []AddNodesItem `opcua:"lengthField=NoOfNodesToAdd"`
}

// AddNodesResponse adds one or more nodes to the server address space.
type AddNodesResponse struct {
	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []AddNodesResult `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

// AddReferencesItem is a request to add a reference to the server address space.
type AddReferencesItem struct {
	SourceNodeId    NodeId
	ReferenceTypeId NodeId
	IsForward       bool
	TargetServerUri string
	TargetNodeId    ExpandedNodeId
	TargetNodeClass NodeClass
}

// AddReferencesRequest adds one or more references to the server address space.
type AddReferencesRequest struct {
	RequestHeader       RequestHeader
	NoOfReferencesToAdd int32
	ReferencesToAdd     []AddReferencesItem `opcua:"lengthField=NoOfReferencesToAdd"`
}

// AddReferencesResponse adds one or more references to the server address space.
type AddReferencesResponse struct {
	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []StatusCode `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

// DeleteNodesItem is a request to delete a node to the server address space.
type DeleteNodesItem struct {
	NodeId                 NodeId
	DeleteTargetReferences bool
}

// DeleteNodesRequest delete one or more nodes from the server address space.
type DeleteNodesRequest struct {
	RequestHeader     RequestHeader
	NoOfNodesToDelete int32
	NodesToDelete     []DeleteNodesItem `opcua:"lengthField=NoOfNodesToDelete"`
}

// DeleteNodesResponse delete one or more nodes from the server address space.
type DeleteNodesResponse struct {
	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []StatusCode `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

// DeleteReferencesItem is a request to delete a node from the server address space.
type DeleteReferencesItem struct {
	SourceNodeId        NodeId
	ReferenceTypeId     NodeId
	IsForward           bool
	TargetNodeId        ExpandedNodeId
	DeleteBidirectional bool
}

// DeleteReferencesRequest delete one or more references from the server address space.
type DeleteReferencesRequest struct {
	RequestHeader          RequestHeader
	NoOfReferencesToDelete int32
	ReferencesToDelete     []DeleteReferencesItem `opcua:"lengthField=NoOfReferencesToDelete"`
}

// DeleteReferencesResponse delete one or more references from the server address space.
type DeleteReferencesResponse struct {
	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []StatusCode `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

// ViewDescription the view to browse.
type ViewDescription struct {
	ViewId      NodeId
	Timestamp   time.Time
	ViewVersion uint32
}

// BrowseDescription is a request to browse the the references from a node.
type BrowseDescription struct {
	NodeId          NodeId
	BrowseDirection BrowseDirection
	ReferenceTypeId NodeId
	IncludeSubtypes bool
	NodeClassMask   uint32
	ResultMask      uint32
}

// ReferenceDescription the description of a reference.
type ReferenceDescription struct {
	ReferenceTypeId NodeId
	IsForward       bool
	NodeId          ExpandedNodeId
	BrowseName      QualifiedName
	DisplayName     LocalizedText
	NodeClass       NodeClass
	TypeDefinition  ExpandedNodeId
}

// BrowseResult the result of a browse operation.
type BrowseResult struct {
	StatusCode        StatusCode
	ContinuationPoint ByteString
	NoOfReferences    int32
	References        []ReferenceDescription `opcua:"lengthField=NoOfReferences"`
}

// BrowseRequest browse the references for one or more nodes from the server address space.
type BrowseRequest struct {
	RequestHeader                 RequestHeader
	View                          ViewDescription
	RequestedMaxReferencesPerNode uint32
	NoOfNodesToBrowse             int32
	NodesToBrowse                 []BrowseDescription `opcua:"lengthField=NoOfNodesToBrowse"`
}

// BrowseResponse browse the references for one or more nodes from the server address space.
type BrowseResponse struct {
	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []BrowseResult `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

// BrowseNextRequest continues one or more browse operations.
type BrowseNextRequest struct {
	RequestHeader             RequestHeader
	ReleaseContinuationPoints bool
	NoOfContinuationPoints    int32
	ContinuationPoints        []ByteString `opcua:"lengthField=NoOfContinuationPoints"`
}

// BrowseNextResponse continues one or more browse operations.
type BrowseNextResponse struct {
	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []BrowseResult `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

// RelativePathElement is an element in a relative path.
type RelativePathElement struct {
	ReferenceTypeId NodeId
	IsInverse       bool
	IncludeSubtypes bool
	TargetName      QualifiedName
}

// RelativePath is a relative path constructed from reference types and browse names.
type RelativePath struct {
	NoOfElements int32
	Elements     []RelativePathElement `opcua:"lengthField=NoOfElements"`
}

// BrowsePath is a request to translate a path into a node id.
type BrowsePath struct {
	StartingNode NodeId
	RelativePath RelativePath
}

// BrowsePathTarget the target of the translated path.
type BrowsePathTarget struct {
	TargetId           ExpandedNodeId
	RemainingPathIndex uint32
}

// BrowsePathResult the result of a translate opearation.
type BrowsePathResult struct {
	StatusCode  StatusCode
	NoOfTargets int32
	Targets     []BrowsePathTarget `opcua:"lengthField=NoOfTargets"`
}

// TranslateBrowsePathsToNodeIdsRequest translates one or more paths in the server address space.
type TranslateBrowsePathsToNodeIdsRequest struct {
	RequestHeader   RequestHeader
	NoOfBrowsePaths int32
	BrowsePaths     []BrowsePath `opcua:"lengthField=NoOfBrowsePaths"`
}

// TranslateBrowsePathsToNodeIdsResponse translates one or more paths in the server address space.
type TranslateBrowsePathsToNodeIdsResponse struct {
	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []BrowsePathResult `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

// RegisterNodesRequest registers one or more nodes for repeated use within a session.
type RegisterNodesRequest struct {
	RequestHeader       RequestHeader
	NoOfNodesToRegister int32
	NodesToRegister     []NodeId `opcua:"lengthField=NoOfNodesToRegister"`
}

// RegisterNodesResponse registers one or more nodes for repeated use within a session.
type RegisterNodesResponse struct {
	ResponseHeader        ResponseHeader
	NoOfRegisteredNodeIds int32
	RegisteredNodeIds     []NodeId `opcua:"lengthField=NoOfRegisteredNodeIds"`
}

// UnregisterNodesRequest unregisters one or more previously registered nodes.
type UnregisterNodesRequest struct {
	RequestHeader         RequestHeader
	NoOfNodesToUnregister int32
	NodesToUnregister     []NodeId `opcua:"lengthField=NoOfNodesToUnregister"`
}

// UnregisterNodesResponse unregisters one or more previously registered nodes.
type UnregisterNodesResponse struct {
	ResponseHeader ResponseHeader
}

type EndpointConfiguration struct {
	OperationTimeout      int32
	UseBinaryEncoding     bool
	MaxStringLength       int32
	MaxByteStringLength   int32
	MaxArrayLength        int32
	MaxMessageSize        int32
	MaxBufferSize         int32
	ChannelLifetime       int32
	SecurityTokenLifetime int32
}

type QueryDataDescription struct {
	RelativePath RelativePath
	AttributeId  uint32
	IndexRange   string
}

type NodeTypeDescription struct {
	TypeDefinitionNode ExpandedNodeId
	IncludeSubTypes    bool
	NoOfDataToReturn   int32
	DataToReturn       []QueryDataDescription `opcua:"lengthField=NoOfDataToReturn"`
}

type QueryDataSet struct {
	NodeId             ExpandedNodeId
	TypeDefinitionNode ExpandedNodeId
	NoOfValues         int32
	Values             []Variant `opcua:"lengthField=NoOfValues"`
}

type NodeReference struct {
	NodeId                NodeId
	ReferenceTypeId       NodeId
	IsForward             bool
	NoOfReferencedNodeIds int32
	ReferencedNodeIds     []NodeId `opcua:"lengthField=NoOfReferencedNodeIds"`
}

type ContentFilterElement struct {
	FilterOperator     FilterOperator
	NoOfFilterOperands int32
	FilterOperands     []ExtensionObject `opcua:"lengthField=NoOfFilterOperands"`
}

type ContentFilter struct {
	NoOfElements int32
	Elements     []ContentFilterElement `opcua:"lengthField=NoOfElements"`
}

type FilterOperand struct {
}

type ElementOperand struct {
	FilterOperand

	Index uint32
}

type LiteralOperand struct {
	FilterOperand

	Value Variant
}

type AttributeOperand struct {
	FilterOperand

	NodeId      NodeId
	Alias       string
	BrowsePath  RelativePath
	AttributeId uint32
	IndexRange  string
}

type SimpleAttributeOperand struct {
	FilterOperand

	TypeDefinitionId NodeId
	NoOfBrowsePath   int32
	BrowsePath       []QualifiedName `opcua:"lengthField=NoOfBrowsePath"`
	AttributeId      uint32
	IndexRange       string
}

type ContentFilterElementResult struct {
	StatusCode                 StatusCode
	NoOfOperandStatusCodes     int32
	OperandStatusCodes         []StatusCode `opcua:"lengthField=NoOfOperandStatusCodes"`
	NoOfOperandDiagnosticInfos int32
	OperandDiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfOperandDiagnosticInfos"`
}

type ContentFilterResult struct {
	NoOfElementResults         int32
	ElementResults             []ContentFilterElementResult `opcua:"lengthField=NoOfElementResults"`
	NoOfElementDiagnosticInfos int32
	ElementDiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfElementDiagnosticInfos"`
}

type ParsingResult struct {
	StatusCode              StatusCode
	NoOfDataStatusCodes     int32
	DataStatusCodes         []StatusCode `opcua:"lengthField=NoOfDataStatusCodes"`
	NoOfDataDiagnosticInfos int32
	DataDiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDataDiagnosticInfos"`
}

type QueryFirstRequest struct {
	RequestHeader         RequestHeader
	View                  ViewDescription
	NoOfNodeTypes         int32
	NodeTypes             []NodeTypeDescription `opcua:"lengthField=NoOfNodeTypes"`
	Filter                ContentFilter
	MaxDataSetsToReturn   uint32
	MaxReferencesToReturn uint32
}

type QueryFirstResponse struct {
	ResponseHeader      ResponseHeader
	NoOfQueryDataSets   int32
	QueryDataSets       []QueryDataSet `opcua:"lengthField=NoOfQueryDataSets"`
	ContinuationPoint   ByteString
	NoOfParsingResults  int32
	ParsingResults      []ParsingResult `opcua:"lengthField=NoOfParsingResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
	FilterResult        ContentFilterResult
}

type QueryNextRequest struct {
	RequestHeader            RequestHeader
	ReleaseContinuationPoint bool
	ContinuationPoint        ByteString
}

type QueryNextResponse struct {
	ResponseHeader           ResponseHeader
	NoOfQueryDataSets        int32
	QueryDataSets            []QueryDataSet `opcua:"lengthField=NoOfQueryDataSets"`
	RevisedContinuationPoint ByteString
}

type ReadValueId struct {
	NodeId       NodeId
	AttributeId  uint32
	IndexRange   string
	DataEncoding QualifiedName
}

type ReadRequest struct {
	RequestHeader      RequestHeader
	MaxAge             float64
	TimestampsToReturn TimestampsToReturn
	NoOfNodesToRead    int32
	NodesToRead        []ReadValueId `opcua:"lengthField=NoOfNodesToRead"`
}

type ReadResponse struct {
	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []DataValue `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type HistoryReadValueId struct {
	NodeId            NodeId
	IndexRange        string
	DataEncoding      QualifiedName
	ContinuationPoint ByteString
}

type HistoryReadResult struct {
	StatusCode        StatusCode
	ContinuationPoint ByteString
	HistoryData       ExtensionObject
}

type HistoryReadDetails struct {
}

type ReadEventDetails struct {
	HistoryReadDetails

	NumValuesPerNode uint32
	StartTime        time.Time
	EndTime          time.Time
	Filter           EventFilter
}

type ReadRawModifiedDetails struct {
	HistoryReadDetails

	IsReadModified   bool
	StartTime        time.Time
	EndTime          time.Time
	NumValuesPerNode uint32
	ReturnBounds     bool
}

type ReadProcessedDetails struct {
	HistoryReadDetails

	StartTime              time.Time
	EndTime                time.Time
	ProcessingInterval     float64
	NoOfAggregateType      int32
	AggregateType          []NodeId `opcua:"lengthField=NoOfAggregateType"`
	AggregateConfiguration AggregateConfiguration
}

type ReadAtTimeDetails struct {
	HistoryReadDetails

	NoOfReqTimes    int32
	ReqTimes        []time.Time `opcua:"lengthField=NoOfReqTimes"`
	UseSimpleBounds bool
}

type HistoryData struct {
	NoOfDataValues int32
	DataValues     []DataValue `opcua:"lengthField=NoOfDataValues"`
}

type ModificationInfo struct {
	ModificationTime time.Time
	UpdateType       HistoryUpdateType
	UserName         string
}

type HistoryModifiedData struct {
	HistoryData

	NoOfDataValues        int32
	DataValues            []DataValue `opcua:"lengthField=NoOfDataValues"`
	NoOfModificationInfos int32
	ModificationInfos     []ModificationInfo `opcua:"lengthField=NoOfModificationInfos"`
}

type HistoryEvent struct {
	NoOfEvents int32
	Events     []HistoryEventFieldList `opcua:"lengthField=NoOfEvents"`
}

type HistoryReadRequest struct {
	RequestHeader             RequestHeader
	HistoryReadDetails        ExtensionObject
	TimestampsToReturn        TimestampsToReturn
	ReleaseContinuationPoints bool
	NoOfNodesToRead           int32
	NodesToRead               []HistoryReadValueId `opcua:"lengthField=NoOfNodesToRead"`
}

type HistoryReadResponse struct {
	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []HistoryReadResult `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type WriteValue struct {
	NodeId      NodeId
	AttributeId uint32
	IndexRange  string
	Value       DataValue
}

type WriteRequest struct {
	RequestHeader    RequestHeader
	NoOfNodesToWrite int32
	NodesToWrite     []WriteValue `opcua:"lengthField=NoOfNodesToWrite"`
}

type WriteResponse struct {
	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []StatusCode `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type HistoryUpdateDetails struct {
	NodeId NodeId
}

type UpdateDataDetails struct {
	HistoryUpdateDetails

	NodeId               NodeId
	PerformInsertReplace PerformUpdateType
	NoOfUpdateValues     int32
	UpdateValues         []DataValue `opcua:"lengthField=NoOfUpdateValues"`
}

type UpdateStructureDataDetails struct {
	HistoryUpdateDetails

	NodeId               NodeId
	PerformInsertReplace PerformUpdateType
	NoOfUpdateValues     int32
	UpdateValues         []DataValue `opcua:"lengthField=NoOfUpdateValues"`
}

type UpdateEventDetails struct {
	HistoryUpdateDetails

	NodeId               NodeId
	PerformInsertReplace PerformUpdateType
	Filter               EventFilter
	NoOfEventData        int32
	EventData            []HistoryEventFieldList `opcua:"lengthField=NoOfEventData"`
}

type DeleteRawModifiedDetails struct {
	HistoryUpdateDetails

	NodeId           NodeId
	IsDeleteModified bool
	StartTime        time.Time
	EndTime          time.Time
}

type DeleteAtTimeDetails struct {
	HistoryUpdateDetails

	NodeId       NodeId
	NoOfReqTimes int32
	ReqTimes     []time.Time `opcua:"lengthField=NoOfReqTimes"`
}

type DeleteEventDetails struct {
	HistoryUpdateDetails

	NodeId       NodeId
	NoOfEventIds int32
	EventIds     []ByteString `opcua:"lengthField=NoOfEventIds"`
}

type HistoryUpdateResult struct {
	StatusCode           StatusCode
	NoOfOperationResults int32
	OperationResults     []StatusCode `opcua:"lengthField=NoOfOperationResults"`
	NoOfDiagnosticInfos  int32
	DiagnosticInfos      []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type HistoryUpdateRequest struct {
	RequestHeader            RequestHeader
	NoOfHistoryUpdateDetails int32
	HistoryUpdateDetails     []ExtensionObject `opcua:"lengthField=NoOfHistoryUpdateDetails"`
}

type HistoryUpdateResponse struct {
	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []HistoryUpdateResult `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type CallMethodRequest struct {
	ObjectId           NodeId
	MethodId           NodeId
	NoOfInputArguments int32
	InputArguments     []Variant `opcua:"lengthField=NoOfInputArguments"`
}

type CallMethodResult struct {
	StatusCode                       StatusCode
	NoOfInputArgumentResults         int32
	InputArgumentResults             []StatusCode `opcua:"lengthField=NoOfInputArgumentResults"`
	NoOfInputArgumentDiagnosticInfos int32
	InputArgumentDiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfInputArgumentDiagnosticInfos"`
	NoOfOutputArguments              int32
	OutputArguments                  []Variant `opcua:"lengthField=NoOfOutputArguments"`
}

type CallRequest struct {
	RequestHeader     RequestHeader
	NoOfMethodsToCall int32
	MethodsToCall     []CallMethodRequest `opcua:"lengthField=NoOfMethodsToCall"`
}

type CallResponse struct {
	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []CallMethodResult `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type MonitoringFilter struct {
}

type DataChangeFilter struct {
	MonitoringFilter

	Trigger       DataChangeTrigger
	DeadbandType  uint32
	DeadbandValue float64
}

type EventFilter struct {
	MonitoringFilter

	NoOfSelectClauses int32
	SelectClauses     []SimpleAttributeOperand `opcua:"lengthField=NoOfSelectClauses"`
	WhereClause       ContentFilter
}

type AggregateConfiguration struct {
	UseServerCapabilitiesDefaults bool
	TreatUncertainAsBad           bool
	PercentDataBad                uint8
	PercentDataGood               uint8
	UseSlopedExtrapolation        bool
}

type AggregateFilter struct {
	MonitoringFilter

	StartTime              time.Time
	AggregateType          NodeId
	ProcessingInterval     float64
	AggregateConfiguration AggregateConfiguration
}

type MonitoringFilterResult struct {
}

type EventFilterResult struct {
	MonitoringFilterResult

	NoOfSelectClauseResults         int32
	SelectClauseResults             []StatusCode `opcua:"lengthField=NoOfSelectClauseResults"`
	NoOfSelectClauseDiagnosticInfos int32
	SelectClauseDiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfSelectClauseDiagnosticInfos"`
	WhereClauseResult               ContentFilterResult
}

type AggregateFilterResult struct {
	MonitoringFilterResult

	RevisedStartTime              time.Time
	RevisedProcessingInterval     float64
	RevisedAggregateConfiguration AggregateConfiguration
}

type MonitoringParameters struct {
	ClientHandle     uint32
	SamplingInterval float64
	Filter           ExtensionObject
	QueueSize        uint32
	DiscardOldest    bool
}

type MonitoredItemCreateRequest struct {
	ItemToMonitor       ReadValueId
	MonitoringMode      MonitoringMode
	RequestedParameters MonitoringParameters
}

type MonitoredItemCreateResult struct {
	StatusCode              StatusCode
	MonitoredItemId         uint32
	RevisedSamplingInterval float64
	RevisedQueueSize        uint32
	FilterResult            ExtensionObject
}

type CreateMonitoredItemsRequest struct {
	RequestHeader      RequestHeader
	SubscriptionId     uint32
	TimestampsToReturn TimestampsToReturn
	NoOfItemsToCreate  int32
	ItemsToCreate      []MonitoredItemCreateRequest `opcua:"lengthField=NoOfItemsToCreate"`
}

type CreateMonitoredItemsResponse struct {
	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []MonitoredItemCreateResult `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type MonitoredItemModifyRequest struct {
	MonitoredItemId     uint32
	RequestedParameters MonitoringParameters
}

type MonitoredItemModifyResult struct {
	StatusCode              StatusCode
	RevisedSamplingInterval float64
	RevisedQueueSize        uint32
	FilterResult            ExtensionObject
}

type ModifyMonitoredItemsRequest struct {
	RequestHeader      RequestHeader
	SubscriptionId     uint32
	TimestampsToReturn TimestampsToReturn
	NoOfItemsToModify  int32
	ItemsToModify      []MonitoredItemModifyRequest `opcua:"lengthField=NoOfItemsToModify"`
}

type ModifyMonitoredItemsResponse struct {
	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []MonitoredItemModifyResult `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type SetMonitoringModeRequest struct {
	RequestHeader        RequestHeader
	SubscriptionId       uint32
	MonitoringMode       MonitoringMode
	NoOfMonitoredItemIds int32
	MonitoredItemIds     []uint32 `opcua:"lengthField=NoOfMonitoredItemIds"`
}

type SetMonitoringModeResponse struct {
	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []StatusCode `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type SetTriggeringRequest struct {
	RequestHeader     RequestHeader
	SubscriptionId    uint32
	TriggeringItemId  uint32
	NoOfLinksToAdd    int32
	LinksToAdd        []uint32 `opcua:"lengthField=NoOfLinksToAdd"`
	NoOfLinksToRemove int32
	LinksToRemove     []uint32 `opcua:"lengthField=NoOfLinksToRemove"`
}

type SetTriggeringResponse struct {
	ResponseHeader            ResponseHeader
	NoOfAddResults            int32
	AddResults                []StatusCode `opcua:"lengthField=NoOfAddResults"`
	NoOfAddDiagnosticInfos    int32
	AddDiagnosticInfos        []DiagnosticInfo `opcua:"lengthField=NoOfAddDiagnosticInfos"`
	NoOfRemoveResults         int32
	RemoveResults             []StatusCode `opcua:"lengthField=NoOfRemoveResults"`
	NoOfRemoveDiagnosticInfos int32
	RemoveDiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfRemoveDiagnosticInfos"`
}

type DeleteMonitoredItemsRequest struct {
	RequestHeader        RequestHeader
	SubscriptionId       uint32
	NoOfMonitoredItemIds int32
	MonitoredItemIds     []uint32 `opcua:"lengthField=NoOfMonitoredItemIds"`
}

type DeleteMonitoredItemsResponse struct {
	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []StatusCode `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type CreateSubscriptionRequest struct {
	RequestHeader               RequestHeader
	RequestedPublishingInterval float64
	RequestedLifetimeCount      uint32
	RequestedMaxKeepAliveCount  uint32
	MaxNotificationsPerPublish  uint32
	PublishingEnabled           bool
	Priority                    uint8
}

type CreateSubscriptionResponse struct {
	ResponseHeader            ResponseHeader
	SubscriptionId            uint32
	RevisedPublishingInterval float64
	RevisedLifetimeCount      uint32
	RevisedMaxKeepAliveCount  uint32
}

type ModifySubscriptionRequest struct {
	RequestHeader               RequestHeader
	SubscriptionId              uint32
	RequestedPublishingInterval float64
	RequestedLifetimeCount      uint32
	RequestedMaxKeepAliveCount  uint32
	MaxNotificationsPerPublish  uint32
	Priority                    uint8
}

type ModifySubscriptionResponse struct {
	ResponseHeader            ResponseHeader
	RevisedPublishingInterval float64
	RevisedLifetimeCount      uint32
	RevisedMaxKeepAliveCount  uint32
}

type SetPublishingModeRequest struct {
	RequestHeader       RequestHeader
	PublishingEnabled   bool
	NoOfSubscriptionIds int32
	SubscriptionIds     []uint32 `opcua:"lengthField=NoOfSubscriptionIds"`
}

type SetPublishingModeResponse struct {
	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []StatusCode `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type NotificationMessage struct {
	SequenceNumber       uint32
	PublishTime          time.Time
	NoOfNotificationData int32
	NotificationData     []ExtensionObject `opcua:"lengthField=NoOfNotificationData"`
}

type NotificationData struct {
}

type DataChangeNotification struct {
	NotificationData

	NoOfMonitoredItems  int32
	MonitoredItems      []MonitoredItemNotification `opcua:"lengthField=NoOfMonitoredItems"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type MonitoredItemNotification struct {
	ClientHandle uint32
	Value        DataValue
}

type EventNotificationList struct {
	NotificationData

	NoOfEvents int32
	Events     []EventFieldList `opcua:"lengthField=NoOfEvents"`
}

type EventFieldList struct {
	ClientHandle    uint32
	NoOfEventFields int32
	EventFields     []Variant `opcua:"lengthField=NoOfEventFields"`
}

type HistoryEventFieldList struct {
	NoOfEventFields int32
	EventFields     []Variant `opcua:"lengthField=NoOfEventFields"`
}

type StatusChangeNotification struct {
	NotificationData

	Status         StatusCode
	DiagnosticInfo *DiagnosticInfo
}

type SubscriptionAcknowledgement struct {
	SubscriptionId uint32
	SequenceNumber uint32
}

type PublishRequest struct {
	RequestHeader                    RequestHeader
	NoOfSubscriptionAcknowledgements int32
	SubscriptionAcknowledgements     []SubscriptionAcknowledgement `opcua:"lengthField=NoOfSubscriptionAcknowledgements"`
}

type PublishResponse struct {
	ResponseHeader               ResponseHeader
	SubscriptionId               uint32
	NoOfAvailableSequenceNumbers int32
	AvailableSequenceNumbers     []uint32 `opcua:"lengthField=NoOfAvailableSequenceNumbers"`
	MoreNotifications            bool
	NotificationMessage          NotificationMessage
	NoOfResults                  int32
	Results                      []StatusCode `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos          int32
	DiagnosticInfos              []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type RepublishRequest struct {
	RequestHeader            RequestHeader
	SubscriptionId           uint32
	RetransmitSequenceNumber uint32
}

type RepublishResponse struct {
	ResponseHeader      ResponseHeader
	NotificationMessage NotificationMessage
}

type TransferResult struct {
	StatusCode                   StatusCode
	NoOfAvailableSequenceNumbers int32
	AvailableSequenceNumbers     []uint32 `opcua:"lengthField=NoOfAvailableSequenceNumbers"`
}

type TransferSubscriptionsRequest struct {
	RequestHeader       RequestHeader
	NoOfSubscriptionIds int32
	SubscriptionIds     []uint32 `opcua:"lengthField=NoOfSubscriptionIds"`
	SendInitialValues   bool
}

type TransferSubscriptionsResponse struct {
	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []TransferResult `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type DeleteSubscriptionsRequest struct {
	RequestHeader       RequestHeader
	NoOfSubscriptionIds int32
	SubscriptionIds     []uint32 `opcua:"lengthField=NoOfSubscriptionIds"`
}

type DeleteSubscriptionsResponse struct {
	ResponseHeader      ResponseHeader
	NoOfResults         int32
	Results             []StatusCode `opcua:"lengthField=NoOfResults"`
	NoOfDiagnosticInfos int32
	DiagnosticInfos     []DiagnosticInfo `opcua:"lengthField=NoOfDiagnosticInfos"`
}

type BuildInfo struct {
	ProductUri       string
	ManufacturerName string
	ProductName      string
	SoftwareVersion  string
	BuildNumber      string
	BuildDate        time.Time
}

type RedundantServerDataType struct {
	ServerId     string
	ServiceLevel uint8
	ServerState  ServerState
}

type EndpointUrlListDataType struct {
	NoOfEndpointUrlList int32
	EndpointUrlList     []string `opcua:"lengthField=NoOfEndpointUrlList"`
}

type NetworkGroupDataType struct {
	ServerUri        string
	NoOfNetworkPaths int32
	NetworkPaths     []EndpointUrlListDataType `opcua:"lengthField=NoOfNetworkPaths"`
}

type SamplingIntervalDiagnosticsDataType struct {
	SamplingInterval           float64
	MonitoredItemCount         uint32
	MaxMonitoredItemCount      uint32
	DisabledMonitoredItemCount uint32
}

type ServerDiagnosticsSummaryDataType struct {
	ServerViewCount               uint32
	CurrentSessionCount           uint32
	CumulatedSessionCount         uint32
	SecurityRejectedSessionCount  uint32
	RejectedSessionCount          uint32
	SessionTimeoutCount           uint32
	SessionAbortCount             uint32
	CurrentSubscriptionCount      uint32
	CumulatedSubscriptionCount    uint32
	PublishingIntervalCount       uint32
	SecurityRejectedRequestsCount uint32
	RejectedRequestsCount         uint32
}

type ServerStatusDataType struct {
	StartTime           time.Time
	CurrentTime         time.Time
	State               ServerState
	BuildInfo           BuildInfo
	SecondsTillShutdown uint32
	ShutdownReason      LocalizedText
}

type SessionDiagnosticsDataType struct {
	SessionId                          NodeId
	SessionName                        string
	ClientDescription                  ApplicationDescription
	ServerUri                          string
	EndpointUrl                        string
	NoOfLocaleIds                      int32
	LocaleIds                          []string `opcua:"lengthField=NoOfLocaleIds"`
	ActualSessionTimeout               float64
	MaxResponseMessageSize             uint32
	ClientConnectionTime               time.Time
	ClientLastContactTime              time.Time
	CurrentSubscriptionsCount          uint32
	CurrentMonitoredItemsCount         uint32
	CurrentPublishRequestsInQueue      uint32
	TotalRequestCount                  ServiceCounterDataType
	UnauthorizedRequestCount           uint32
	ReadCount                          ServiceCounterDataType
	HistoryReadCount                   ServiceCounterDataType
	WriteCount                         ServiceCounterDataType
	HistoryUpdateCount                 ServiceCounterDataType
	CallCount                          ServiceCounterDataType
	CreateMonitoredItemsCount          ServiceCounterDataType
	ModifyMonitoredItemsCount          ServiceCounterDataType
	SetMonitoringModeCount             ServiceCounterDataType
	SetTriggeringCount                 ServiceCounterDataType
	DeleteMonitoredItemsCount          ServiceCounterDataType
	CreateSubscriptionCount            ServiceCounterDataType
	ModifySubscriptionCount            ServiceCounterDataType
	SetPublishingModeCount             ServiceCounterDataType
	PublishCount                       ServiceCounterDataType
	RepublishCount                     ServiceCounterDataType
	TransferSubscriptionsCount         ServiceCounterDataType
	DeleteSubscriptionsCount           ServiceCounterDataType
	AddNodesCount                      ServiceCounterDataType
	AddReferencesCount                 ServiceCounterDataType
	DeleteNodesCount                   ServiceCounterDataType
	DeleteReferencesCount              ServiceCounterDataType
	BrowseCount                        ServiceCounterDataType
	BrowseNextCount                    ServiceCounterDataType
	TranslateBrowsePathsToNodeIdsCount ServiceCounterDataType
	QueryFirstCount                    ServiceCounterDataType
	QueryNextCount                     ServiceCounterDataType
	RegisterNodesCount                 ServiceCounterDataType
	UnregisterNodesCount               ServiceCounterDataType
}

type SessionSecurityDiagnosticsDataType struct {
	SessionId               NodeId
	ClientUserIdOfSession   string
	NoOfClientUserIdHistory int32
	ClientUserIdHistory     []string `opcua:"lengthField=NoOfClientUserIdHistory"`
	AuthenticationMechanism string
	Encoding                string
	TransportProtocol       string
	SecurityMode            MessageSecurityMode
	SecurityPolicyUri       string
	ClientCertificate       ByteString
}

type ServiceCounterDataType struct {
	TotalCount uint32
	ErrorCount uint32
}

type StatusResult struct {
	StatusCode     StatusCode
	DiagnosticInfo *DiagnosticInfo
}

type SubscriptionDiagnosticsDataType struct {
	SessionId                    NodeId
	SubscriptionId               uint32
	Priority                     uint8
	PublishingInterval           float64
	MaxKeepAliveCount            uint32
	MaxLifetimeCount             uint32
	MaxNotificationsPerPublish   uint32
	PublishingEnabled            bool
	ModifyCount                  uint32
	EnableCount                  uint32
	DisableCount                 uint32
	RepublishRequestCount        uint32
	RepublishMessageRequestCount uint32
	RepublishMessageCount        uint32
	TransferRequestCount         uint32
	TransferredToAltClientCount  uint32
	TransferredToSameClientCount uint32
	PublishRequestCount          uint32
	DataChangeNotificationsCount uint32
	EventNotificationsCount      uint32
	NotificationsCount           uint32
	LatePublishRequestCount      uint32
	CurrentKeepAliveCount        uint32
	CurrentLifetimeCount         uint32
	UnacknowledgedMessageCount   uint32
	DiscardedMessageCount        uint32
	MonitoredItemCount           uint32
	DisabledMonitoredItemCount   uint32
	MonitoringQueueOverflowCount uint32
	NextSequenceNumber           uint32
	EventQueueOverFlowCount      uint32
}

type ModelChangeStructureDataType struct {
	Affected     NodeId
	AffectedType NodeId
	Verb         uint8
}

type SemanticChangeStructureDataType struct {
	Affected     NodeId
	AffectedType NodeId
}

type Range struct {
	Low  float64
	High float64
}

type EUInformation struct {
	NamespaceUri string
	UnitId       int32
	DisplayName  LocalizedText
	Description  LocalizedText
}

type ComplexNumberType struct {
	Real      float32
	Imaginary float32
}

type DoubleComplexNumberType struct {
	Real      float64
	Imaginary float64
}

type AxisInformation struct {
	EngineeringUnits EUInformation
	EURange          Range
	Title            LocalizedText
	AxisScaleType    AxisScaleEnumeration
	NoOfAxisSteps    int32
	AxisSteps        []float64 `opcua:"lengthField=NoOfAxisSteps"`
}

type XVType struct {
	X     float64
	Value float32
}

type ProgramDiagnosticDataType struct {
	CreateSessionId               NodeId
	CreateClientName              string
	InvocationCreationTime        time.Time
	LastTransitionTime            time.Time
	LastMethodCall                string
	LastMethodSessionId           NodeId
	NoOfLastMethodInputArguments  int32
	LastMethodInputArguments      []Argument `opcua:"lengthField=NoOfLastMethodInputArguments"`
	NoOfLastMethodOutputArguments int32
	LastMethodOutputArguments     []Argument `opcua:"lengthField=NoOfLastMethodOutputArguments"`
	LastMethodCallTime            time.Time
	LastMethodReturnStatus        StatusResult
}

type Annotation struct {
	Message        string
	UserName       string
	AnnotationTime time.Time
}
